// Labores de nómina = hoja «Lista_Labores» del RDT (Agrosoft): [código, nombre, unidad].
// Ordenadas por uso en Don Gaspar (registro dic-2025 a sep-2026) y luego alfabéticas, para
// que las sugerencias muestren primero las de la finca. El nombre va tal cual al RDT.

const UNIDADES = {
  hora: 'horas', hectarea: 'ha', unidad: 'unidades', dia: 'días', racimo: 'racimos', caja: 'cajas', metro: 'metros',
  mts: 'metros', tonelada: 't', bulto: 'bultos', jornal: 'jornales', prestacion: 'prestación', semilla: 'semillas',
  kilo: 'kg', palma: 'palmas',
};
// Unidades que se reportan por lote en el RDT (lote + área/cantidad).
const POR_LOTE = new Set(['hectarea', 'unidad', 'racimo', 'metro', 'mts', 'palma', 'semilla']);

const FILAS = [
  ['334', 'Corte caja integral', 'caja'],
  ['23', 'Deshoje', 'hectarea'],
  ['90', 'Dominical promediado', 'hora'],
  ['336', 'Corte promedio', 'caja'],
  ['50381', 'Desflore e identificacion', 'hectarea'],
  ['58', 'Coordinador de campo', 'hora'],
  ['91', 'Festivo promediado', 'hora'],
  ['72', 'Riego', 'hora'],
  ['1006', 'Dominical promediado parcela', 'hora'],
  ['100', 'Auxilio de transporte', 'dia'],
  ['500277', 'Corte al dia', 'hora'],
  ['335', 'Corte caja integral festivo', 'caja'],
  ['207', 'Dominical promediado admon', 'hora'],
  ['162', 'Administrador finca', 'hora'],
  ['50096', 'Celaduria', 'hora'],
  ['445', 'Control de maleza al dia', 'hora'],
  ['500341', 'Coordinador de empacadora', 'hora'],
  ['500425', 'Almacenista', 'hora'],
  ['409', 'Descargue de carton h.e.d.', 'hora'],
  ['500148', 'Riego h.e.d.', 'hora'],
  ['258', 'Botada de vastago', 'unidad'],
  ['500349', 'Limpia con guadaña al dia', 'hora'],
  ['3', 'Coordinador general', 'hora'],
  ['5', 'Desmache con palin', 'hectarea'],
  ['104', 'Chapia de canal', 'metro'],
  ['70', 'Motorista', 'hora'],
  ['754', 'Embolse y amarre cinta morada', 'racimo'],
  ['750', 'Embolse y amarre cinta cafe', 'racimo'],
  ['71', 'Motorista h.e.d.', 'hora'],
  ['755', 'Embolse y amarre cinta amarilla', 'racimo'],
  ['756', 'Embolse y amarre cinta roja', 'racimo'],
  ['751', 'Embolse y amarre cinta azul', 'racimo'],
  ['752', 'Embolse y amarre cinta blanca', 'racimo'],
  ['656', 'Aplicacion de fertilizante und', 'bulto'],
  ['96', 'Levante de manguera', 'hora'],
  ['150', 'Vacaciones', 'dia'],
  ['893', 'Mantenimiento de riego adm Maroma', 'hora'],
  ['620', 'Auxiliar de casino', 'hora'],
  ['749', 'Embolse y amarre cinta verde', 'racimo'],
  ['1007', 'Festivo promediado parcela', 'hora'],
  ['696', 'Yumbolon cinta blanca', 'racimo'],
  ['1028', 'Control de maleza moko', 'hora'],
  ['753', 'Embolse y amarre cinta negra', 'racimo'],
  ['492', 'Corte promedio rechazo', 'caja'],
  ['995', 'Ayudante de fumigacion aerea', 'hora'],
  ['500302', 'Limpia con guadaña', 'hectarea'],
  ['699', 'Yumbolon cinta amarilla', 'racimo'],
  ['596', 'Mantenimiento de manguera', 'hora'],
  ['695', 'Yumbolon cinta azul', 'racimo'],
  ['561', 'Corte promedio cablero', 'caja'],
  ['698', 'Yumbolon cinta morada', 'racimo'],
  ['693', 'Yumbolon cinta verde', 'racimo'],
  ['1029', 'Deshoje moko al dia', 'hora'],
  ['945', 'Corte promedio bioseguridad', 'caja'],
  ['500203', 'Operador retroexcavadora', 'hora'],
  ['151', 'Incapacidad general', 'hora'],
  ['208', 'Festivo promediado admon', 'hora'],
  ['404', 'Bioseguridad', 'hora'],
  ['189', 'Cablero', 'hora'],
  ['720', 'Integracion empresa', 'hora'],
  ['256', 'Mantenimiento de riego', 'hora'],
  ['259', 'Aseo de empacadora', 'hora'],
  ['50050', 'Control de moko', 'hora'],
  ['955', 'Proteccion de fruta al dia', 'hora'],
  ['405', 'Cargue de cajas h.e.d.', 'hora'],
  ['500263', 'Celaduria dominical', 'hora'],
  ['50382', 'Desflore e identificacion festivo', 'hectarea'],
  ['50035', 'Resiembra de troncon', 'unidad'],
  ['500415', 'Auxilio de rodamiento', 'dia'],
  ['700', 'Yumbolon cinta roja', 'racimo'],
  ['694', 'Yumbolon cinta cafe', 'racimo'],
  ['771', 'Dominical promediado riego', 'hora'],
  ['102', 'Ausente', 'hora'],
  ['697', 'Yumbolon cinta negra', 'racimo'],
  ['2412', 'Mantenimiento de resiembra', 'hora'],
  ['111', 'Corte caja integral dominical', 'caja'],
  ['50041', 'Llenada de rechazo', 'hora'],
  ['317', 'Mantenimiento de riego adm', 'hora'],
  ['500112', 'Limpia de jarillon', 'hora'],
  ['1119', 'Pegada de yumbolon', 'hora'],
  ['500182', 'Corte promedio festivo', 'caja'],
  ['1117', 'Sanidad vegetal El Habra', 'hora'],
  ['500319', 'Desbejuque', 'hectarea'],
  ['500331', 'Descanso compensatorio', 'hora'],
  ['88', 'Celaduria compensatorio', 'hora'],
  ['888', 'Dominical promediado mantenimientos adm', 'hora'],
  ['9887', 'Repique de matas', 'hora'],
  ['773', 'Dominical promediado motor', 'hora'],
  ['500174', 'Mantenimiento de infraestructura', 'hora'],
  ['500210', 'Chapia de canal al dia', 'hora'],
  ['158', 'Vivero', 'hora'],
  ['50053', 'Aseo de bodega', 'hora'],
  ['50083', 'Aseo de plantacion', 'hora'],
  ['370', 'Proteccion quema de sol al dia', 'hora'],
  ['500179', 'Corte promedio al dia', 'hora'],
  ['766', 'Dominical promediado maquinaria', 'hora'],
  ['494', 'Mantenimiento retroexcavadora', 'hora'],
  ['121', 'Permiso no remunerado', 'hora'],
  ['772', 'Festivo promediado riego', 'hora'],
  ['500151', 'Mantenimiento de riego h.e.d.', 'hora'],
  ['500261', 'Celaduria festivo', 'hora'],
  ['253', 'Bonificacion por cajas', 'caja'],
  ['316', 'Siembra', 'unidad'],
  ['500462', 'Corte mercado nacional', 'hora'],
  ['185', 'Deshoje festivo', 'hectarea'],
  ['890', 'Auxilio de transporte mantenimientos adm', 'dia'],
  ['1062', 'Control de insectos El Habra', 'hora'],
  ['781', 'Bonificacion fertilizacion', 'dia'],
  ['500262', 'Desmache al dia', 'hora'],
  ['500161', 'Riego festivo', 'hora'],
  ['1122', 'Botada de vastago festivo', 'unidad'],
  ['769', 'Festivo promediado celaduria', 'hora'],
  ['130', 'Limpia de linderos al dia', 'hora'],
  ['500168', 'Riego dominical', 'hora'],
  ['1026', 'Fertilizacion El Habra', 'hora'],
  ['1001', 'Auxilio de transporte maquinaria', 'dia'],
  ['499', 'Descargue de fertilizante h.e.d.', 'hora'],
  ['767', 'Festivo promediado maquinaria', 'hora'],
  ['774', 'Festivo promediado motor', 'hora'],
  ['889', 'Festivo promediado mantenimientos adm', 'hora'],
  ['1144', 'Aplicacion foliar El Habra', 'hora'],
  ['500393', 'Control de poblacion', 'hora'],
  ['1075', 'Desbejuque moko al dia', 'hora'],
  ['329', 'Licencia por luto', 'hora'],
  ['50049', 'Limpia de canal de riego', 'hora'],
  ['273', 'Motorista dominical', 'hora'],
  ['48', 'Recava de canal', 'metro'],
  ['639', 'Aseo cable via', 'hora'],
  ['160', 'Aseo general', 'hora'],
  ['50077', 'Conteo de cinta', 'hora'],
  ['444', 'Control de maleza', 'hectarea'],
  ['500352', 'Deshoje al dia', 'hora'],
  ['810', 'Embolse y amarre cinta amarilla festivo', 'unidad'],
  ['500300', 'Hechura de puente', 'hora'],
  ['180', 'Horometro retroexcavadora', 'hora'],
  ['271', 'Motorista festivo', 'hora'],
  ['957', 'Botada de vastago al dia', 'hora'],
  ['500181', 'Desbejuque al dia', 'hora'],
  ['557', 'Motorista festivo h.e.d.', 'hora'],
  ['401', 'Recuperacion de yumbolon', 'hora'],
  ['500372', 'Acarreo de semillas', 'hora'],
  ['500187', 'Almacenista festivo', 'hora'],
  ['636', 'Auxiliar de casino festivo', 'hora'],
  ['506', 'Corte promedio rechazo festivo', 'caja'],
  ['235', 'Descargue de carton', 'hora'],
  ['500259', 'Incapacidad por accidente', 'hora'],
  ['83', 'Instalacion de riego', 'hora'],
  ['386', 'Limpia de reservorio', 'hora'],
  ['50078', 'Mantenimiento de garruchas', 'hora'],
  ['500361', 'Mantenimiento de guadaña', 'hora'],
  ['895', 'Mantenimiento de riego adm El Refugio', 'hora'],
  ['500249', 'Mantenimiento de vivero', 'hora'],
  ['101', 'Permiso', 'hora'],
  ['667', 'Permiso por lluvia', 'hora'],
  ['22', 'Reamarre al dia', 'hora'],
  ['962', 'Aseo de casa administrativa', 'hora'],
  ['946', 'Corte promedio bioseguridad festivo', 'caja'],
  ['113', 'Corte promedio dominical', 'caja'],
  ['785', 'Corte promedio rechazo al dia', 'unidad'],
  ['768', 'Dominical promediado celaduria', 'hora'],
  ['1044', 'Mantenimiento de cerca moko', 'hora'],
  ['631', 'Mantenimiento de manguera h.e.d.', 'hora'],
  ['1153', 'Marcacion de espacios para siembra', 'hora'],
  ['215', 'Menor valor pagado prd anterior', 'unidad'],
  ['574', 'Motorista dominical h.e.d.', 'hora'],
  ['205', 'Resiembras', 'hora'],
  ['310', 'Transporte de matas', 'hora'],
  ['123', 'Arranque de troncon', 'hora'],
  ['1025', 'Ayudante de fumigacion aerea dominical', 'hora'],
  ['1018', 'Ayudante de fumigacion aerea festivo', 'hora'],
  ['469', 'Bioseguridad festivo', 'hora'],
  ['298', 'Clasificacion de yumbolon', 'hora'],
  ['572', 'Corte promedio cablero festivo', 'caja'],
  ['500397', 'Desguasque', 'hectarea'],
  ['500180', 'Desguasque al dia', 'hora'],
  ['112', 'Permiso por calamidad familiar', 'hora'],
  ['500417', 'Recoleccion de plastico', 'hora'],
  ['6', 'Saldo pendiente dominical promediado', 'hora'],
  ['500423', 'Acarreo de troncon', 'hora'],
  ['252', 'Bonificacion por cajas admon', 'caja'],
  ['951', 'Botada de fruta pulpa crema', 'hora'],
  ['1073', 'Desmache con palin festivo', 'hectarea'],
  ['3335', 'Hechura de escalera', 'hora'],
  ['1100', 'Limpia de linderos moko al dia', 'hora'],
  ['82', 'Mantenimiento de cable via', 'hora'],
  ['69', 'Mantenimiento de motor', 'hora'],
  ['621', 'Mantenimiento de pediluvio', 'hora'],
  ['183', 'Permiso por cita medica', 'hora'],
  ['1004', 'Permiso por enfermedad', 'hora'],
  ['126', 'Pintura', 'hora'],
  ['1011', 'Reamarre y desvio', 'hora'],
  ['50063', 'Suspendido', 'hora'],
  ['272', 'Acarreo de matas para siembra', 'hora'],
  ['500362', 'Agricultura', 'hora'],
  ['38', 'Aplicacion de fertilizante al dia', 'hora'],
  ['905', 'Aseo de empacadora movil', 'hora'],
  ['1027', 'Colocacion de carpa moko', 'hora'],
  ['1043', 'Colocacion de pase cola', 'hora'],
  ['500234', 'Desagüe de canal', 'hora'],
  ['1093', 'Desbejuque al dia El Habra', 'hora'],
  ['411', 'Descargue de insumos h.e.d.', 'hora'],
  ['1137', 'Desflore e identificacion dominical', 'hectarea'],
  ['192', 'Elaboracion de vivero', 'hora'],
  ['161', 'Engrase de cable via', 'hora'],
  ['118', 'Limpia guadaña empacadora', 'hora'],
  ['163', 'Mantenimiento de cerca', 'hora'],
  ['668', 'No aporta incapacidad', 'hora'],
  ['2424', 'Precalibracion', 'hora'],
  ['526', 'Riego dominical h.e.d.', 'hora'],
  ['500358', 'Saldo pendiente auxilio transporte', 'dia'],
  ['500270', 'Saldo pendiente corte', 'unidad'],
  ['800', 'Saldo pendiente incapacidad', 'hora'],
  ['763', 'Saldo pendiente motorista', 'hora'],
  ['115', 'Almacenista dominical', 'hora'],
  ['687', 'Arreglo de patio racimo', 'hora'],
  ['156', 'Aseo de patio', 'hora'],
  ['977', 'Auxiliar de casino dominical', 'hora'],
  ['996', 'Ayudante de fumigacion aerea h.e.d.', 'hora'],
  ['500093', 'Bonificacion', 'dia'],
  ['50076', 'Botada de basura', 'hora'],
  ['30', 'Colocacion de yumbolon', 'unidad'],
  ['1072', 'Control de maleza moko al dia festivo', 'hora'],
  ['1139', 'Corte promedio cablero dominical', 'caja'],
  ['1014', 'Corte promedio moko', 'unidad'],
  ['522', 'Deshoje dominical', 'hectarea'],
  ['500454', 'Devolucion descuento', 'unidad'],
  ['34', 'Hechura de antenas al dia', 'hora'],
  ['745', 'Hechura de zanja', 'metro'],
  ['292', 'Identificacion de cintas', 'hora'],
  ['26', 'Limpia a machete', 'hora'],
  ['500279', 'Llenada de bolsas vivero', 'unidad'],
  ['924', 'Mantenimiento de riego adm dominical', 'hora'],
  ['674', 'Mantenimiento de riego adm festivo', 'hora'],
  ['894', 'Mantenimiento de riego adm Maria Laura', 'hora'],
  ['1058', 'Mantenimiento de riego El Habra', 'hora'],
  ['50', 'Oficios varios', 'hora'],
  ['1146', 'Organizacion de casino', 'hora'],
  ['658', 'Preparacion de vivero', 'hora'],
  ['981', 'Repique de arbol caido', 'hora'],
  ['998', 'Retroactivo incremento salarial', 'dia'],
  ['75', 'Riego festivo h.e.d.', 'hora'],
  ['1005', 'Saldo pendiente control de poblacion', 'hora'],
  ['11', 'Saldo pendiente fertilizacion', 'unidad'],
  ['1010', 'Saldo pendiente rodamiento', 'dia'],
  ['534', 'Siembra al dia', 'hora'],
  ['549', 'Acarreo de abono', 'hora'],
  ['500468', 'Acarreo de arena', 'hora'],
  ['655', 'Acarreo de arena h.e.d.', 'hora'],
  ['105', 'Acarreo de bolsas vivero', 'hora'],
  ['436', 'Acarreo de cal agricola', 'hora'],
  ['451', 'Acarreo de carton', 'hora'],
  ['500110', 'Acarreo de estibas', 'unidad'],
  ['500215', 'Acarreo de fertilizante', 'hora'],
  ['340', 'Acarreo de fruta', 'hora'],
  ['500257', 'Acarreo de gallinaza', 'hora'],
  ['423', 'Acarreo de madera', 'hora'],
  ['45', 'Acarreo de material de riego', 'hora'],
  ['659', 'Acarreo de pase cola', 'hora'],
  ['172', 'Acarreo de plastico', 'hora'],
  ['95', 'Acarreo de racimos gondola', 'hora'],
  ['50067', 'Acarreo materiales cable via', 'hora'],
  ['1090', 'Acomodo de fruta mula', 'hora'],
  ['2627', 'Adecuacion de baños', 'hora'],
  ['500284', 'Adecuacion de bodega', 'hora'],
  ['50039', 'Adecuacion de semilleros', 'hora'],
  ['500230', 'Adecuacion de tuberias', 'hora'],
  ['217', 'Administacion festivo', 'hora'],
  ['1', 'Administrador', 'hora'],
  ['500379', 'Administrador finca La Alegria', 'hora'],
  ['346', 'Administrador Palmawa', 'hora'],
  ['193', 'Agricultura El Refugio', 'hora'],
  ['568', 'Agricultura h.e.d.', 'hora'],
  ['250', 'Ajuste de prima semestral', 'prestacion'],
  ['511', 'Alineacion de mangueras', 'hora'],
  ['567', 'Alineacion de mangueras h.e.d.', 'hora'],
  ['500222', 'Alineacion de plantillas', 'hora'],
  ['1045', 'Alineacion en vivero', 'hora'],
  ['351', 'Alineacion para resiembra', 'hora'],
  ['500218', 'Alineacion para siembra', 'hora'],
  ['301', 'Alineacion para siembra dominical', 'hora'],
  ['500395', 'Alistamiento (amarre y daipa)', 'racimo'],
  ['500400', 'Alistamiento cinta gris', 'racimo'],
  ['500399', 'Alistamiento cinta naranja', 'racimo'],
  ['500392', 'Alistamiento cinta negra', 'racimo'],
  ['500394', 'Alistamiento cinta verde', 'racimo'],
  ['500382', 'Alistamiento de racimos', 'racimo'],
  ['500381', 'Alistamiento finca Don Gaspar', 'racimo'],
  ['361', 'Alistamiento racim. amarilla', 'unidad'],
  ['359', 'Alistamiento racim. azul', 'unidad'],
  ['360', 'Alistamiento racim. blanca', 'unidad'],
  ['362', 'Alistamiento racim. morada', 'unidad'],
  ['357', 'Alistamiento racim. negro', 'unidad'],
  ['363', 'Alistamiento racim. roja', 'unidad'],
  ['358', 'Alistamiento racimos', 'hora'],
  ['597', 'Alta paricion', 'racimo'],
  ['681', 'Alta paricion festivo', 'racimo'],
  ['679', 'Alta paricion Maroma', 'racimo'],
  ['662', 'Amarre', 'racimo'],
  ['32', 'Amarre al dia', 'hora'],
  ['1031', 'Amarre al dia El Refugio', 'hora'],
  ['179', 'Amarre al dia festivo', 'hora'],
  ['916', 'Amarre al dia festivo', 'hora'],
  ['708', 'Amarre cinta amarilla', 'racimo'],
  ['704', 'Amarre cinta azul', 'racimo'],
  ['737', 'Amarre cinta beige', 'unidad'],
  ['705', 'Amarre cinta blanca', 'racimo'],
  ['703', 'Amarre cinta cafe', 'racimo'],
  ['701', 'Amarre cinta gris', 'racimo'],
  ['760', 'Amarre cinta mecate', 'unidad'],
  ['707', 'Amarre cinta morada', 'racimo'],
  ['706', 'Amarre cinta negra', 'racimo'],
  ['709', 'Amarre cinta roja', 'racimo'],
  ['702', 'Amarre cinta verde', 'racimo'],
  ['50044', 'Amarre de bacota plantilla', 'hora'],
  ['678', 'Amarre El Refugio', 'unidad'],
  ['50118', 'Amarre eliz cristina', 'hora'],
  ['500153', 'Amarre en plantilla', 'hora'],
  ['671', 'Amarre Maroma', 'unidad'],
  ['1265', 'Amarre por hectarea', 'hectarea'],
  ['412', 'Amarre y desflore', 'hora'],
  ['320', 'Amarre y reamarre', 'hectarea'],
  ['419', 'Amarre y reamarre al dia', 'hora'],
  ['324', 'Amarre y reamarre festivo', 'hectarea'],
  ['500359', 'Analisis de suelo calicata', 'hora'],
  ['500439', 'Analista contable', 'dia'],
  ['500442', 'Analista de materiales', 'dia'],
  ['500443', 'Analista de produccion', 'dia'],
  ['465', 'Anticipo sueldo adm', 'dia'],
  ['33', 'Apertura bolsa de empaque', 'dia'],
  ['85', 'Apertura de bolsas de campo', 'unidad'],
  ['1051', 'Apertura de bolsas de campo al dia', 'hora'],
  ['500433', 'Apertura de daipa', 'hora'],
  ['570', 'Aplicacion abono organico y abotek dominical', 'hectarea'],
  ['571', 'Aplicacion abono y fertilizante', 'hectarea'],
  ['500401', 'Aplicacion con barreno', 'unidad'],
  ['500315', 'Aplicacion con barreno por hora', 'hora'],
  ['922', 'Aplicacion de abono', 'hectarea'],
  ['500404', 'Aplicacion de abono', 'bulto'],
  ['959', 'Aplicacion de abono al dia dominical', 'hora'],
  ['147', 'Aplicacion de abono El Refugio', 'bulto'],
  ['500474', 'Aplicacion de abono El Refugio', 'bulto'],
  ['307', 'Aplicacion de abono festivo', 'bulto'],
  ['170', 'Aplicacion de abono organico', 'unidad'],
  ['171', 'Aplicacion de abono organico al dia', 'hora'],
  ['500242', 'Aplicacion de abotek', 'hora'],
  ['928', 'Aplicacion de azufre', 'hora'],
  ['413', 'Aplicacion de cal', 'hora'],
  ['500228', 'Aplicacion de compost', 'hectarea'],
  ['136', 'Aplicacion de fertilizante Elizabeth', 'bulto'],
  ['138', 'Aplicacion de fertilizante Elizabeth por hora', 'hora'],
  ['312', 'Aplicacion de fertilizante festivo', 'bulto'],
  ['481', 'Aplicacion de fertilizante h.e.d.', 'hora'],
  ['304', 'Aplicacion de fertilizante plantilla', 'hora'],
  ['403', 'Aplicacion de fertilizante plantilla', 'bulto'],
  ['311', 'Aplicacion de fertilizante plantilla festivo', 'hora'],
  ['29', 'Aplicacion de fertilizante por hectarea', 'hectarea'],
  ['385', 'Aplicacion de fertilizante proyecto por hora', 'hora'],
  ['200260', 'Aplicacion de fertilizante troncon', 'unidad'],
  ['50068', 'Aplicacion de fertilizante troncon al dia', 'hora'],
  ['478', 'Aplicacion de fungicida', 'hora'],
  ['31', 'Aplicacion de gallinaza', 'hectarea'],
  ['24', 'Aplicacion de herbicida', 'hectarea'],
  ['500260', 'Aplicacion de herbicida al dia', 'hora'],
  ['1013', 'Aplicacion de herbicida al dia dominical', 'hectarea'],
  ['958', 'Aplicacion de herbicida al dia festivo', 'hectarea'],
  ['869', 'Aplicacion de herbicida al dia Maria Laura', 'hectarea'],
  ['500217', 'Aplicacion de herbicida El Refugio por hora', 'hora'],
  ['500194', 'Aplicacion de herbicida Elizabeth', 'hectarea'],
  ['586', 'Aplicacion de herbicida maiz dominical', 'hora'],
  ['865', 'Aplicacion de herbicida Maria Laura', 'hectarea'],
  ['605', 'Aplicacion de herbicida Maroma al dia', 'hora'],
  ['604', 'Aplicacion de herbicida Maroma al dia festivo', 'hora'],
  ['318', 'Aplicacion de herbicida plantilla', 'hora'],
  ['500460', 'Aplicacion de herbicida por hora Elizabeth', 'hora'],
  ['352', 'Aplicacion de herbicida proyecto', 'hora'],
  ['50040', 'Aplicacion de kcl', 'hectarea'],
  ['539', 'Aplicacion de limo', 'hora'],
  ['927', 'Aplicacion de mezcla especial', 'hora'],
  ['39', 'Aplicacion de nitrato de potasio', 'hectarea'],
  ['500103', 'Aplicacion de round up', 'hectarea'],
  ['500102', 'Aplicacion de round up por hora', 'hora'],
  ['410', 'Aplicacion de trichoderma', 'hora'],
  ['50034', 'Aplicacion de urea', 'bulto'],
  ['50031', 'Aplicacion de urea al dia', 'hora'],
  ['19', 'Aplicacion de wuxal por hora', 'hora'],
  ['281', 'Aplicacion de yeso', 'hectarea'],
  ['533', 'Aplicacion de yeso al dia', 'hora'],
  ['214', 'Aplicacion de zinc', 'hora'],
  ['446', 'Aplicacion drench', 'hora'],
  ['500241', 'Aplicacion foliar al dia', 'hora'],
  ['489', 'Aplicacion foliar bomba', 'hectarea'],
  ['487', 'Aplicacion foliar cacorro', 'hectarea'],
  ['137', 'Aplicacion foliar Elizabeth', 'hora'],
  ['177', 'Aplicacion foliar festivo', 'hora'],
  ['373', 'Aplicacion foliar plantilla', 'hora'],
  ['500236', 'Aplicacion foliar proyecto', 'hora'],
  ['66', 'Aplicacion mezcla sigatoka y foliar', 'hectarea'],
  ['332', 'Aporque de matas', 'hora'],
  ['500461', 'Aporque de plantilla', 'unidad'],
  ['500240', 'Aporque de plantilla al dia', 'hora'],
  ['1080', 'Apoyo en cargue de fruta mula', 'tonelada'],
  ['500402', 'Aprendiz sena', 'hora'],
  ['500448', 'Aprendiz sena administracion', 'dia'],
  ['933', 'Aprendiz sena festivo', 'hora'],
  ['877', 'Aprendiz sena lectivo administracion', 'dia'],
  ['500418', 'Aprendiz universitario', 'hora'],
  ['53', 'Aprov. matas caidas', 'hora'],
  ['154', 'Arada de tierra', 'hora'],
  ['50042', 'Arranque de arboles', 'hora'],
  ['643', 'Arranque de bacotas', 'hora'],
  ['500343', 'Arranque de bejuco', 'hora'],
  ['612', 'Arranque de pajon', 'hora'],
  ['857', 'Arranque de pajon festivo', 'hora'],
  ['2897', 'Arranque de semillas', 'hora'],
  ['650', 'Arreglo area rechazo', 'hora'],
  ['50052', 'Arreglo de bodega', 'hora'],
  ['510', 'Arreglo de bodega h.e.d.', 'hora'],
  ['500344', 'Arreglo de bolsas', 'hora'],
  ['519', 'Arreglo de camino', 'hora'],
  ['520', 'Arreglo de camino h.e.d.', 'hora'],
  ['500297', 'Arreglo de canal', 'hora'],
  ['581', 'Arreglo de carruchas', 'hora'],
  ['500109', 'Arreglo de carton', 'hora'],
  ['1020', 'Arreglo de chanelas', 'hora'],
  ['483', 'Arreglo de cintas', 'hora'],
  ['500283', 'Arreglo de daipa', 'hora'],
  ['201', 'Arreglo de derrumbe', 'hora'],
  ['500427', 'Arreglo de dique', 'hora'],
  ['887', 'Arreglo de divisiones', 'hora'],
  ['353', 'Arreglo de escaleras', 'hora'],
  ['638', 'Arreglo de pallet', 'hora'],
  ['140', 'Arreglo de pase cola', 'hora'],
  ['56', 'Arreglo de plantilla', 'hora'],
  ['148', 'Arreglo de porton', 'hora'],
  ['500298', 'Arreglo de puentes', 'hora'],
  ['50033', 'Arreglo de semilleros', 'hora'],
  ['50018', 'Arreglo de sequia', 'hora'],
  ['500291', 'Arreglo de techo', 'hora'],
  ['50075', 'Arreglo de terreno para siembra', 'hora'],
  ['1036', 'Arreglo de trincho', 'hora'],
  ['2896', 'Arreglo trincheras con saco', 'hora'],
  ['734', 'Arreglo tuberias sanitarias', 'hora'],
  ['455', 'Arreglo via', 'hora'],
  ['1203', 'Aseo de baños', 'hora'],
  ['1000', 'Aseo de casa Elizabeth', 'hora'],
  ['50027', 'Aseo de empacadora Elizabeth', 'hora'],
  ['303', 'Aseo de empacadora festivo', 'hora'],
  ['547', 'Aseo de empacadora h.e.d.', 'hora'],
  ['736', 'Aseo de empacadora Maroma', 'hora'],
  ['248', 'Aseo de piscina empacadora', 'hora'],
  ['569', 'Aseo de protectores', 'hora'],
  ['777', 'Asesor de sistema de gestion', 'dia'],
  ['414', 'Asistente de contabilidad', 'dia'],
  ['500478', 'Asistente juridico', 'dia'],
  ['587', 'Auditor', 'dia'],
  ['50098', 'Ausente por calamidad', 'hora'],
  ['541', 'Auxiliar', 'hora'],
  ['500094', 'Auxiliar de campo', 'hora'],
  ['439', 'Auxiliar de campo festivo', 'hora'],
  ['500318', 'Auxiliar de cosecha', 'hora'],
  ['500378', 'Auxiliar de cosecha Don Gaspar', 'hora'],
  ['500134', 'Auxiliar de empacadora', 'hora'],
  ['1138', 'Auxiliar de empacadora dominical', 'hora'],
  ['500195', 'Auxiliar de empacadora Elizabeth', 'hora'],
  ['593', 'Auxiliar de empacadora festivo', 'hora'],
  ['500152', 'Auxiliar de empacadora h.e.d.', 'hora'],
  ['473', 'Auxiliar de inventario', 'hora'],
  ['500405', 'Auxiliar de nomina', 'dia'],
  ['1086', 'Auxiliar de oficina', 'hora'],
  ['1115', 'Auxiliar de oficina festivo', 'hora'],
  ['50099', 'Auxiliar de sena', 'hora'],
  ['573', 'Auxiliar festivo', 'hora'],
  ['500403', 'Auxilio', 'dia'],
  ['500128', 'Auxilio de alimentacion', 'dia'],
  ['1110', 'Auxilio de alimentacion dron', 'dia'],
  ['1082', 'Auxilio de alimentacion El Habra', 'dia'],
  ['1021', 'Auxilio de alimentacion El Refugio', 'dia'],
  ['775', 'Auxilio de alimentacion La Alegria', 'dia'],
  ['832', 'Auxilio de alimentacion Maria Laura', 'dia'],
  ['415', 'Auxilio de rodamiento adm', 'dia'],
  ['416', 'Auxilio de transporte adm', 'dia'],
  ['1077', 'Auxilio de transporte aprendiz finca', 'dia'],
  ['966', 'Auxilio de transporte transporte', 'dia'],
  ['181', 'Auxilio de vivienda', 'dia'],
  ['500369', 'Auxilio medico', 'hora'],
  ['500287', 'Ayudante de albañil', 'hora'],
  ['297', 'Ayudante de albañil dominical', 'hora'],
  ['57', 'Ayudante de albañil Elizabeth', 'hora'],
  ['500509', 'Ayudante de albañil h.e.d.', 'hora'],
  ['828', 'Ayudante de albañil Maroma', 'hora'],
  ['500104', 'Ayudante de amarre', 'hora'],
  ['565', 'Ayudante de aplicacion de azufre', 'hora'],
  ['500127', 'Ayudante de bulldozer', 'hora'],
  ['542', 'Ayudante de bulldozer dominical', 'hora'],
  ['614', 'Ayudante de bulldozer festivo', 'hora'],
  ['500226', 'Ayudante de cable via', 'hora'],
  ['279', 'Ayudante de construccion vivero', 'hora'],
  ['1009', 'Ayudante de control de maleza al dia', 'hora'],
  ['50081', 'Ayudante de corte', 'hora'],
  ['92', 'Ayudante de fertirriego', 'hora'],
  ['98', 'Ayudante de instalacion de riego', 'hora'],
  ['339', 'Ayudante de instalacion electrica dominical', 'hora'],
  ['1065', 'Ayudante de mecanico', 'hora'],
  ['500436', 'Ayudante de medicion de canal', 'hora'],
  ['284', 'Ayudante de moko', 'hora'],
  ['691', 'Ayudante de moko festivo', 'hora'],
  ['689', 'Ayudante de motosierra', 'hora'],
  ['500396', 'Ayudante de parcela', 'hora'],
  ['664', 'Ayudante de parcela El Refugio', 'hora'],
  ['108', 'Ayudante de parcela Elizabeth', 'hora'],
  ['500456', 'Ayudante de parcela festivo', 'hora'],
  ['610', 'Ayudante de parcela Maroma', 'hora'],
  ['500154', 'Ayudante de parcela plantilla', 'hora'],
  ['963', 'Ayudante de prueba arbol', 'hora'],
  ['500336', 'Ayudante de retro', 'hora'],
  ['500455', 'Ayudante de retro festivo', 'hora'],
  ['119', 'Ayudante de riego', 'hora'],
  ['50069', 'Ayudante de topografo', 'hora'],
  ['500324', 'Ayudante de tractor', 'hora'],
  ['295', 'Ayudante de vivero', 'hora'],
  ['291', 'Ayudante de vivero dominical', 'hora'],
  ['294', 'Ayudante de vivero festivo', 'hora'],
  ['500135', 'Bajada de bolsa', 'hora'],
  ['500136', 'Bajada de bolsa Elizabeth', 'hora'],
  ['843', 'Bajada de manguera', 'hora'],
  ['786', 'Banano para ganado', 'hora'],
  ['1059', 'Bioseguridad dominical', 'hora'],
  ['1083', 'Bonificacion de riego', 'dia'],
  ['792', 'Bonificacion motor', 'dia'],
  ['540', 'Bonificacion parcela', 'unidad'],
  ['1034', 'Bonificacion por cajas El Refugio', 'caja'],
  ['949', 'Bonificacion por cajas Maria Laura', 'caja'],
  ['1150', 'Botada de basura Don Gaspar', 'hora'],
  ['500430', 'Botada de corona', 'hora'],
  ['500428', 'Botada de jamiche', 'hora'],
  ['500200', 'Botada de plastico', 'hora'],
  ['787', 'Botada de rechazo', 'hora'],
  ['503', 'Botada de residuos solidos', 'hora'],
  ['1066', 'Bufalero', 'hora'],
  ['305', 'Busqueda de bufalo', 'hora'],
  ['898', 'Busqueda de mapaitero', 'hora'],
  ['978', 'Cablero dominical', 'hora'],
  ['393', 'Cablero festivo', 'hora'],
  ['500149', 'Cablero h.e.d.', 'hora'],
  ['500312', 'Caciqueo', 'unidad'],
  ['500119', 'Caciqueo al dia', 'hora'],
  ['500159', 'Caciqueo en plantilla', 'hora'],
  ['382', 'Caciqueo plantilla proyecto', 'hora'],
  ['399', 'Caja campo rechazada', 'unidad'],
  ['397', 'Caja empacadora rechazada', 'unidad'],
  ['326', 'Caja integral rechazada', 'unidad'],
  ['328', 'Caja promedio auxiliar rechazada', 'unidad'],
  ['400', 'Caja promedio campo rechazada', 'unidad'],
  ['398', 'Caja promedio empacadora rechazada', 'unidad'],
  ['327', 'Caja promedio rechazada', 'unidad'],
  ['500227', 'Calibracion de bomba', 'hora'],
  ['257', 'Cambio de boquilla', 'hora'],
  ['220', 'Cambio de cinta', 'dia'],
  ['500350', 'Canalero', 'hora'],
  ['470', 'Canastilla rechazo', 'hora'],
  ['500229', 'Capacitacion', 'hora'],
  ['500452', 'Capacitacion en corte', 'hora'],
  ['611', 'Capacitacion en corte festivo', 'hora'],
  ['829', 'Capacitacion en corte La Alegria', 'hora'],
  ['466', 'Capacitacion en desmache', 'hora'],
  ['578', 'Capacitacion en fertilizacion', 'hora'],
  ['1076', 'Capacitacion en inspeccion de fruta y almacen', 'hora'],
  ['622', 'Capacitacion en parcela', 'hora'],
  ['500106', 'Capacitacion en riego', 'hora'],
  ['623', 'Capacitacion en yumbolon', 'hora'],
  ['1111', 'Capataz de cosecha.', 'hora'],
  ['356', 'Cargue de cajas', 'hora'],
  ['1141', 'Cargue de cajas dominical h.e.d.', 'hora'],
  ['500167', 'Cargue de cajas Elizabeth', 'hora'],
  ['590', 'Cargue de cajas festivo h.e.d.', 'hora'],
  ['524', 'Cargue de cajas h.e.n.', 'hora'],
  ['504', 'Cargue de carton h.e.d.', 'hora'],
  ['1145', 'Cargue de fertilizante', 'hora'],
  ['1016', 'Cargue de fertilizante h.e.d.', 'tonelada'],
  ['554', 'Cargue de filtro de riego', 'hora'],
  ['276', 'Cargue de fruta mula', 'tonelada'],
  ['1130', 'Cargue de fruta mula al dia', 'hora'],
  ['819', 'Cargue de fruta mula dominical', 'tonelada'],
  ['1102', 'Cargue de fruta mula festivo', 'tonelada'],
  ['1098', 'Cargue de madera', 'hora'],
  ['1135', 'Cargue de madera El Habra', 'hora'],
  ['500355', 'Cargue de materiales', 'hora'],
  ['964', 'Cargue de palma mula h.e.d.', 'hora'],
  ['606', 'Cargue de plantas h.e.d.', 'hora'],
  ['173', 'Cargue de plastico', 'hora'],
  ['1143', 'Cargue de plastico Don Gaspar', 'hora'],
  ['50043', 'Cargue de rechazo', 'hora'],
  ['476', 'Cargue de rechazo h.e.d.', 'hora'],
  ['477', 'Cargue de rechazo h.e.n.', 'hora'],
  ['323', 'Cargue de residuos solidos retro', 'hora'],
  ['1037', 'Cargue de tierra para Don Gaspar', 'hora'],
  ['500330', 'Cargue de tuberia', 'hora'],
  ['837', 'Cargue de tuberia Don Gaspar', 'hora'],
  ['551', 'Cargue de tuberia h.e.d.', 'hora'],
  ['838', 'Cargue de tuberia h.e.d. Don Gaspar', 'hora'],
  ['500107', 'Cargue de vastagos', 'hora'],
  ['836', 'Cargue vivero mula palma', 'hora'],
  ['880', 'Cargue vivero palma', 'hora'],
  ['51', 'Cargue y descargue abono', 'hora'],
  ['1133', 'Cargue y descargue de abono h.e.d.', 'hora'],
  ['166', 'Cargue y descargue de carton', 'unidad'],
  ['288', 'Cargue y descargue de fertilizante', 'hora'],
  ['1079', 'Castreo El Habra', 'hora'],
  ['17', 'Cavada de carretera', 'mts'],
  ['80', 'Celaduria canal de riego', 'hora'],
  ['440', 'Celaduria dominical h.e.d.', 'hora'],
  ['1068', 'Celaduria El Habra', 'hora'],
  ['1069', 'Celaduria El Habra dominical', 'hora'],
  ['1070', 'Celaduria El Habra festivo', 'hora'],
  ['441', 'Celaduria festivo h.e.d.', 'hora'],
  ['500150', 'Celaduria h.e.d.', 'hora'],
  ['106', 'Celaduria h.e.n.', 'dia'],
  ['461', 'Celaduria maquinaria', 'hora'],
  ['462', 'Celaduria maquinaria dominical', 'hora'],
  ['468', 'Celaduria maquinaria festivo', 'hora'],
  ['447', 'Celaduria motor', 'hora'],
  ['448', 'Celaduria motor dominical', 'hora'],
  ['459', 'Celaduria motor festivo', 'hora'],
  ['484', 'Celaduria motor h.e.d.', 'hora'],
  ['500223', 'Celaduria nocturna', 'hora'],
  ['500293', 'Celaduria nocturna festivo', 'hora'],
  ['500183', 'Celaduria porton', 'hora'],
  ['500186', 'Celaduria porton dominical', 'hora'],
  ['500184', 'Celaduria porton festivo', 'hora'],
  ['437', 'Celaduria porton festivo h.e.d.', 'hora'],
  ['428', 'Celaduria porton h.e.d.', 'hora'],
  ['30120', 'Certificacion norma', 'hora'],
  ['209', 'Cesantias', 'prestacion'],
  ['200', 'Cesantias e intereses ocasional', 'prestacion'],
  ['64', 'Chapia de canal al dia festivo', 'hora'],
  ['107', 'Chapia de canal con guadaña', 'metro'],
  ['417', 'Chapia de canal con guadaña al dia', 'hora'],
  ['333', 'Chapia de canal con herbicida al dia', 'hora'],
  ['500172', 'Chapia de canal Elizabeth', 'metro'],
  ['133', 'Chapia de canal por hora Elizabeth', 'hora'],
  ['251', 'Chapia de canal primario', 'metro'],
  ['500139', 'Chapia de canal proyecto', 'metro'],
  ['36', 'Chapia de canal secundario', 'metro'],
  ['856', 'Chapia de canal secundario festivo', 'metro'],
  ['868', 'Chapia de canal secundario Maria Laura', 'metro'],
  ['1002', 'Chop bag', 'hora'],
  ['1204', 'Clasificacion de bolsas', 'hora'],
  ['592', 'Clasificacion de carton', 'hora'],
  ['479', 'Clasificacion de cintas', 'hora'],
  ['237', 'Clasificacion de reciclaje', 'hora'],
  ['1055', 'Clasificacion de semillas', 'hora'],
  ['683', 'Clasificacion de yumbolon Maroma', 'hora'],
  ['4', 'Colocacion de daipa', 'unidad'],
  ['500105', 'Colocacion de microaspersores', 'hora'],
  ['500138', 'Colocacion de polysombra', 'hora'],
  ['508', 'Colocacion de sacos', 'hora'],
  ['1151', 'Colocacion de sacos en canal', 'hora'],
  ['1046', 'Colocacion de techo y piso vivero', 'hora'],
  ['345', 'Colocacion de yumbolon al dia', 'hora'],
  ['195', 'Colocacion de yumbolon El Refugio', 'unidad'],
  ['500141', 'Colocacion de yumbolon Elizabeth', 'unidad'],
  ['275', 'Colocacion de yumbolon festivo', 'unidad'],
  ['531', 'Colocacion de yumbolon festivo Maroma', 'unidad'],
  ['529', 'Colocacion de yumbolon Maroma', 'unidad'],
  ['500351', 'Colocacion punto cinta', 'hora'],
  ['76', 'Compesatorio', 'hora'],
  ['722', 'Compostell', 'hora'],
  ['500438', 'Conductor', 'dia'],
  ['500449', 'Conductor camion', 'dia'],
  ['500408', 'Conductor tractomula', 'jornal'],
  ['921', 'Conductor tractomula dominical', 'jornal'],
  ['882', 'Conductor tractomula festivo', 'jornal'],
  ['84', 'Construccion de alberca', 'hora'],
  ['500282', 'Construccion de alberca', 'hora'],
  ['500299', 'Construccion de canal', 'metro'],
  ['18', 'Construccion de canal al dia', 'hora'],
  ['500311', 'Construccion de canal proyecto', 'mts'],
  ['500310', 'Construccion de canal secundario', 'metro'],
  ['500108', 'Construccion de cerca', 'hora'],
  ['500092', 'Construccion de cerca h.e.d.', 'hora'],
  ['1040', 'Construccion de cerca moko', 'hora'],
  ['460', 'Construccion de corral', 'hora'],
  ['632', 'Construccion de empinaderos', 'hora'],
  ['537', 'Construccion de malla', 'hora'],
  ['299', 'Contador', 'dia'],
  ['500224', 'Conteo de aspersores', 'hora'],
  ['633', 'Conteo de fertilizante', 'hora'],
  ['293', 'Conteo de fruta', 'hora'],
  ['282', 'Conteo de plantas por viento', 'hora'],
  ['155', 'Conteo de poblacion', 'hora'],
  ['1063', 'Conteo de racimos', 'hora'],
  ['498', 'Control de insectos', 'hora'],
  ['1136', 'Control de maleza al dia dominical', 'hora'],
  ['1071', 'Control de maleza al dia festivo', 'hora'],
  ['867', 'Control de maleza al dia Maria Laura', 'hora'],
  ['1123', 'Control de maleza empacadora', 'hectarea'],
  ['598', 'Control de maleza festivo', 'hectarea'],
  ['870', 'Control de maleza manual', 'hora'],
  ['546', 'Control de moko h.e.d.', 'hora'],
  ['788', 'Control de moko Maroma', 'hora'],
  ['500143', 'Control de poblacion Elizabeth', 'hora'],
  ['841', 'Control de poblacion festivo', 'hora'],
  ['500429', 'Control erwinia', 'hora'],
  ['458', 'Control moko festivo', 'hora'],
  ['500441', 'Coordinador certificaciones', 'hora'],
  ['532', 'Coordinador de calidad', 'hora'],
  ['630', 'Coordinador de cosecha', 'hora'],
  ['500370', 'Coordinador de empacadora dga', 'hora'],
  ['500446', 'Coordinador de poblacion', 'hora'],
  ['599', 'Coordinador de produccion', 'hora'],
  ['500447', 'Coordinador de riego', 'hora'],
  ['500197', 'Coordinador de sanidad', 'hora'],
  ['1096', 'Coordinador de siembra', 'hora'],
  ['1061', 'Coordinador El Habra', 'hora'],
  ['500342', 'Coordinador El Refugio', 'hora'],
  ['50086', 'Coordinador festivo', 'hora'],
  ['500386', 'Coordinador general Don Gaspar', 'hora'],
  ['500398', 'Coordinador general Maria Laura', 'hora'],
  ['374', 'Coordinador general zona sur', 'hora'],
  ['2', 'Coordinador La Alegria', 'hora'],
  ['500118', 'Coordinador Maria Laura', 'hora'],
  ['125', 'Coordinador Palmawa', 'hora'],
  ['500339', 'Coordinador produccion', 'hora'],
  ['1149', 'Corazo de flecha palma', 'hora'],
  ['982', 'Corte al dia dominical', 'hora'],
  ['500380', 'Corte al dia Don Gaspar', 'hora'],
  ['500192', 'Corte al dia Elizabeth', 'hora'],
  ['814', 'Corte al dia festivo', 'hora'],
  ['669', 'Corte al dia Maroma', 'hora'],
  ['233', 'Corte apoyo corte', 'dia'],
  ['226', 'Corte baja vastago', 'dia'],
  ['216', 'Corte caja integral Elizabeth', 'unidad'],
  ['642', 'Corte caja integral festivo Maroma', 'unidad'],
  ['644', 'Corte caja integral Maria Laura', 'unidad'],
  ['536', 'Corte caja integral Maroma', 'unidad'],
  ['647', 'Corte caja integral Maroma festivo', 'unidad'],
  ['342', 'Corte campo', 'unidad'],
  ['434', 'Corte campo festivo', 'unidad'],
  ['153', 'Corte de bambu', 'hora'],
  ['60', 'Corte de caña', 'hora'],
  ['530', 'Corte de madera', 'hora'],
  ['500232', 'Corte de madera para estaca', 'hora'],
  ['50071', 'Corte de matas renovacion', 'hora'],
  ['1015', 'Corte de tallos', 'hora'],
  ['1019', 'Corte de tallos', 'hora'],
  ['500410', 'Corte Don Gaspar pega caja/palletizador', 'caja'],
  ['500464', 'Corte El Refugio', 'unidad'],
  ['500465', 'Corte El Refugio al dia', 'hora'],
  ['500467', 'Corte El Refugio festivo', 'unidad'],
  ['221', 'Corte empacadora', 'unidad'],
  ['500409', 'Corte empacadora Don Gaspar', 'caja'],
  ['432', 'Corte empacadora festivo', 'unidad'],
  ['935', 'Corte empacadora movil', 'unidad'],
  ['901', 'Corte empacadora movil al dia', 'jornal'],
  ['902', 'Corte empacadora movil al dia festivo', 'jornal'],
  ['936', 'Corte empacadora movil festivo', 'unidad'],
  ['225', 'Corte evalua/calida', 'dia'],
  ['234', 'Corte festi. apoyo corte', 'dia'],
  ['232', 'Corte festi. baja vastago', 'dia'],
  ['227', 'Corte festi. empacadora', 'caja'],
  ['231', 'Corte festi. evalua calidad', 'dia'],
  ['230', 'Corte festi. inspector', 'dia'],
  ['229', 'Corte festi. palletizador', 'caja'],
  ['228', 'Corte festi. racimos', 'caja'],
  ['500388', 'Corte festivo Don Gaspar', 'hora'],
  ['500389', 'Corte festivo Elizabeth', 'caja'],
  ['500360', 'Corte finca alegria al dia', 'hora'],
  ['224', 'Corte inspector', 'hora'],
  ['500463', 'Corte mercado nacional festivo', 'hora'],
  ['500422', 'Corte o poda de arboles', 'hora'],
  ['223', 'Corte palletizador', 'unidad'],
  ['97', 'Corte palma al dia', 'hora'],
  ['218', 'Corte palma dominical', 'kilo'],
  ['983', 'Corte promedio al dia dominical', 'hora'],
  ['500193', 'Corte promedio al dia Elizabeth', 'hora'],
  ['815', 'Corte promedio al dia festivo', 'hora'],
  ['670', 'Corte promedio al dia Maroma', 'hora'],
  ['947', 'Corte promedio arrumador', 'unidad'],
  ['948', 'Corte promedio arrumador festivo', 'unidad'],
  ['500444', 'Corte promedio auxiliar', 'unidad'],
  ['236', 'Corte promedio auxiliar al dia', 'hora'],
  ['114', 'Corte promedio auxiliar dominical', 'unidad'],
  ['500445', 'Corte promedio auxiliar Elizabeth', 'unidad'],
  ['500450', 'Corte promedio auxiliar festivo', 'unidad'],
  ['986', 'Corte promedio bioseguridad al dia', 'hora'],
  ['985', 'Corte promedio bioseguridad al dia dominical', 'hora'],
  ['976', 'Corte promedio bioseguridad dominical', 'caja'],
  ['343', 'Corte promedio campo', 'unidad'],
  ['435', 'Corte promedio campo festivo', 'unidad'],
  ['196', 'Corte promedio El Refugio', 'unidad'],
  ['337', 'Corte promedio Elizabeth', 'unidad'],
  ['341', 'Corte promedio empacadora', 'unidad'],
  ['433', 'Corte promedio empacadora festivo', 'unidad'],
  ['903', 'Corte promedio empacadora movil', 'jornal'],
  ['937', 'Corte promedio empacadora movil', 'unidad'],
  ['904', 'Corte promedio empacadora movil festivo', 'jornal'],
  ['938', 'Corte promedio empacadora movil festivo', 'unidad'],
  ['491', 'Corte promedio evaluacion', 'unidad'],
  ['507', 'Corte promedio evaluacion festivo', 'unidad'],
  ['535', 'Corte promedio Maria Laura', 'unidad'],
  ['645', 'Corte promedio Maria Laura', 'unidad'],
  ['719', 'Corte promedio Maroma', 'unidad'],
  ['1032', 'Corte promedio moko festivo', 'unidad'],
  ['939', 'Corte promedio palletizador', 'unidad'],
  ['940', 'Corte promedio palletizador festivo', 'unidad'],
  ['941', 'Corte promedio pega caja', 'unidad'],
  ['942', 'Corte promedio pega caja festivo', 'unidad'],
  ['984', 'Corte promedio rechazo al dia dominical', 'hora'],
  ['975', 'Corte promedio rechazo dominical', 'caja'],
  ['943', 'Corte promedio surtidor', 'unidad'],
  ['944', 'Corte promedio surtidor festivo', 'unidad'],
  ['222', 'Corte racimos', 'racimo'],
  ['500309', 'Corte racimos caidos', 'hora'],
  ['500202', 'Cortes de cajas no planillados', 'unidad'],
  ['1091', 'Cosecha de palma al dia', 'hora'],
  ['219', 'Cosecha palma', 'tonelada'],
  ['543', 'Cosecha palma dominical', 'tonelada'],
  ['862', 'Cosecha palma festivo', 'tonelada'],
  ['500267', 'Cosntruccion de puente', 'hora'],
  ['500316', 'Definicion en plantilla', 'hora'],
  ['8', 'Desague en plantacion', 'racimo'],
  ['1109', 'Desague palma', 'hora'],
  ['1108', 'Desague palma festivo', 'hora'],
  ['28', 'Desagüe en plantacion', 'hora'],
  ['131', 'Desarme de vivero', 'hora'],
  ['500390', 'Desbacote de matas', 'hora'],
  ['672', 'Desbejuque al dia El Refugio', 'hora'],
  ['842', 'Desbejuque al dia festivo', 'hora'],
  ['500142', 'Desbejuque Elizabeth', 'hora'],
  ['500178', 'Desbejuque en plantilla', 'hora'],
  ['260', 'Desbloqueo de canal', 'hora'],
  ['37', 'Desbloqueo jarillon', 'hora'],
  ['931', 'Desborone de terrones', 'hora'],
  ['500419', 'Desbunche de racimos', 'hora'],
  ['182', 'Descargue de abono', 'tonelada'],
  ['1088', 'Descargue de abono al dia', 'hora'],
  ['512', 'Descargue de arena', 'hora'],
  ['371', 'Descargue de bloques', 'hora'],
  ['954', 'Descargue de carton dominical', 'hora'],
  ['657', 'Descargue de carton Don Gaspar h.e.d.', 'hora'],
  ['278', 'Descargue de cisco', 'hora'],
  ['50032', 'Descargue de fertilizante', 'tonelada'],
  ['1099', 'Descargue de fertilizante al dia dominical', 'tonelada'],
  ['7210', 'Descargue de gallinaza', 'hora'],
  ['500295', 'Descargue de gravilla festivo', 'hora'],
  ['500280', 'Descargue de insumos', 'hora'],
  ['923', 'Descargue de insumos dominical', 'hora'],
  ['474', 'Descargue de insumos h.e.n.', 'hora'],
  ['500173', 'Descargue de materiales de riego', 'hora'],
  ['408', 'Descargue de materiales h.e.n.', 'hora'],
  ['500101', 'Descargue de pallet', 'unidad'],
  ['602', 'Descargue de plantas h.e.d.', 'hora'],
  ['500368', 'Descargue de semillas', 'hora'],
  ['576', 'Descargue de semillas h.e.d.', 'hora'],
  ['50389', 'Desflore al dia', 'hora'],
  ['950', 'Desflore e identificacion al dia', 'hora'],
  ['1049', 'Desflore e identificacion al dia festivo', 'hora'],
  ['500383', 'Desflore finca Maria Laura', 'hectarea'],
  ['500424', 'Desflore y embolse', 'hectarea'],
  ['1264', 'Desflore, identificacion y embolse', 'hectarea'],
  ['129', 'Desguasque El Refugio por hora', 'hora'],
  ['500247', 'Deshermane', 'hectarea'],
  ['402', 'Deshermane al dia', 'hora'],
  ['500374', 'Deshermane Don Gaspar', 'hectarea'],
  ['389', 'Deshermane festivo', 'hectarea'],
  ['608', 'Deshermane Maroma', 'hectarea'],
  ['500096', 'Deshoje al dia dominical', 'hora'],
  ['500198', 'Deshoje al dia festivo', 'hora'],
  ['500245', 'Deshoje de plantilla', 'hectarea'],
  ['49', 'Deshoje Don Gaspar', 'hectarea'],
  ['270', 'Deshoje El Refugio', 'hectarea'],
  ['500144', 'Deshoje Elizabeth', 'hectarea'],
  ['866', 'Deshoje Maria Laura', 'hectarea'],
  ['680', 'Deshoje Maroma', 'hectarea'],
  ['609', 'Deshoje Maroma al dia', 'hora'],
  ['1041', 'Deshoje moko', 'hectarea'],
  ['1050', 'Deshoje moko al dia festivo', 'hora'],
  ['267', 'Deshoje por hora El Refugio', 'hora'],
  ['463', 'Desmache al dia festivo', 'hora'],
  ['897', 'Desmache al dia La Alegria', 'hora'],
  ['875', 'Desmache al dia Maroma', 'hora'],
  ['178', 'Desmache al dia refugio', 'hora'],
  ['500146', 'Desmache con macana Elizabeth', 'hectarea'],
  ['872', 'Desmache con macana Maroma', 'hectarea'],
  ['110', 'Desmache con macana plantilla', 'hectarea'],
  ['25', 'Desmache con sable', 'hectarea'],
  ['194', 'Desmache con sable El Refugio', 'hectarea'],
  ['500453', 'Desmache con sable festivo', 'hectarea'],
  ['50084', 'Desmache con sable plantilla', 'hectarea'],
  ['791', 'Desmane en campo', 'hora'],
  ['500371', 'Desmonte de area', 'hora'],
  ['286', 'Desmonte de camino', 'hora'],
  ['99', 'Desmonte de vivero', 'hora'],
  ['262', 'Despalille', 'hora'],
  ['500098', 'Despeche', 'hora'],
  ['321', 'Despeche y desvio', 'hectarea'],
  ['740', 'Despeche y desvio al dia', 'hora'],
  ['50094', 'Despunte', 'hora'],
  ['139', 'Despunte de sigatoka', 'hora'],
  ['746', 'Destape de manguera', 'hora'],
  ['109', 'Destape de sifon', 'hora'],
  ['308', 'Destape de tuberias', 'hora'],
  ['313', 'Destape de tuberias festivo', 'hora'],
  ['1132', 'Destronque El Habra', 'hora'],
  ['427', 'Desvare de contenedor h.e.d.', 'hora'],
  ['500131', 'Desvare de tractomula', 'hora'],
  ['500385', 'Desvio de puyon', 'hora'],
  ['500413', 'Desvio de racimos', 'hectareas'],
  ['500406', 'Director general', 'dia'],
  ['802', 'Dominical promediado adm', 'hora'],
  ['1022', 'Dominical promediado adm El Refugio', 'dia'],
  ['782', 'Dominical promediado adm La Alegria', 'dia'],
  ['833', 'Dominical promediado adm Maria Laura', 'dia'],
  ['907', 'Dominical promediado aprendiz finca', 'hora'],
  ['761', 'Dominical promediado transporte', 'jornal'],
  ['50037', 'Dominical promediado y corte', 'hora'],
  ['453', 'Drenaje via', 'hora'],
  ['50048', 'Elaboracion de cazasombra', 'hora'],
  ['50038', 'Elaboracion de compost', 'hora'],
  ['50073', 'Elaboracion de estaca', 'hora'],
  ['500169', 'Elaboracion de puentes proyecto', 'hora'],
  ['331', 'Elaboracion de terminales', 'dia'],
  ['175', 'Elaboracion tulas yumbolon', 'hora'],
  ['20', 'Embolse al dia', 'hora'],
  ['527', 'Embolse al dia festivo', 'hora'],
  ['717', 'Embolse cinta amarilla', 'racimo'],
  ['730', 'Embolse cinta amarilla Maroma', 'unidad'],
  ['713', 'Embolse cinta azul', 'racimo'],
  ['726', 'Embolse cinta azul Maroma', 'unidad'],
  ['735', 'Embolse cinta beige', 'unidad'],
  ['739', 'Embolse cinta beige Maroma', 'unidad'],
  ['714', 'Embolse cinta blanca', 'racimo'],
  ['727', 'Embolse cinta blanca Maroma', 'unidad'],
  ['712', 'Embolse cinta cafe', 'racimo'],
  ['725', 'Embolse cinta cafe Maroma', 'unidad'],
  ['710', 'Embolse cinta gris', 'racimo'],
  ['723', 'Embolse cinta gris Maroma', 'unidad'],
  ['741', 'Embolse cinta mecate', 'unidad'],
  ['742', 'Embolse cinta mecate festivo', 'unidad'],
  ['716', 'Embolse cinta morada', 'racimo'],
  ['729', 'Embolse cinta morada Maroma', 'unidad'],
  ['715', 'Embolse cinta negra', 'racimo'],
  ['728', 'Embolse cinta negra Maroma', 'unidad'],
  ['718', 'Embolse cinta roja', 'racimo'],
  ['731', 'Embolse cinta roja Maroma', 'unidad'],
  ['711', 'Embolse cinta verde', 'racimo'],
  ['724', 'Embolse cinta verde Maroma', 'unidad'],
  ['9', 'Embolse Elizabeth cristina', 'hora'],
  ['528', 'Embolse Maroma', 'hora'],
  ['900', 'Embolse y amarre', 'hectarea'],
  ['874', 'Embolse y amarre al dia', 'hora'],
  ['806', 'Embolse y amarre cinta azul festivo', 'unidad'],
  ['757', 'Embolse y amarre cinta beige', 'racimo'],
  ['812', 'Embolse y amarre cinta beige festivo', 'unidad'],
  ['807', 'Embolse y amarre cinta blanca festivo', 'unidad'],
  ['805', 'Embolse y amarre cinta cafe festivo', 'unidad'],
  ['748', 'Embolse y amarre cinta gris', 'racimo'],
  ['803', 'Embolse y amarre cinta gris festivo', 'unidad'],
  ['758', 'Embolse y amarre cinta mecate', 'racimo'],
  ['813', 'Embolse y amarre cinta mecate festivo', 'unidad'],
  ['809', 'Embolse y amarre cinta morada festivo', 'unidad'],
  ['808', 'Embolse y amarre cinta negra festivo', 'unidad'],
  ['811', 'Embolse y amarre cinta roja festivo', 'unidad'],
  ['804', 'Embolse y amarre cinta verde festivo', 'unidad'],
  ['987', 'Embolse y amarre dominical', 'hectarea'],
  ['925', 'Embolse y amarre festivo', 'hectarea'],
  ['682', 'Embolse y desflore', 'unidad'],
  ['418', 'Embolse y desflore al dia', 'hora'],
  ['770', 'Embolse y desflore al dia festivo', 'hora'],
  ['675', 'Embolse y desflore El Refugio restivo', 'hectarea'],
  ['666', 'Embolse y desflore Maroma', 'hectarea'],
  ['684', 'Embolse y desflore Maroma', 'unidad'],
  ['673', 'Embolse y desflore refugio', 'hectarea'],
  ['319', 'Embolse, desflore e identificacion', 'hectarea'],
  ['330', 'Embolse, desflore e identificacion festivo', 'hectarea'],
  ['827', 'Empaque de fruta por viento', 'hora'],
  ['860', 'Enderezada de matas', 'hora'],
  ['52', 'Engrase de garruchas', 'dia'],
  ['300', 'Entrega de plantas vivero', 'hora'],
  ['566', 'Erradicacion de palma', 'hora'],
  ['407', 'Erradicacion foc', 'hora'],
  ['500289', 'Escavacion de tuberia', 'hora'],
  ['149', 'Escolta', 'dia'],
  ['500209', 'Estaquillada', 'hora'],
  ['500253', 'Estaquillado de plantas', 'hora'],
  ['314', 'Estirada de manguera', 'hora'],
  ['564', 'Estirada de manguera h.e.d.', 'hora'],
  ['372', 'Estirada de manguera proyecto', 'hora'],
  ['493', 'Evaluacion de campo', 'hora'],
  ['486', 'Evaluacion de parcela', 'unidad'],
  ['523', 'Evento empresa', 'hora'],
  ['582', 'Fertilizacion palma', 'hora'],
  ['86', 'Fertirriego', 'hora'],
  ['500164', 'Fertirriego Elizabeth h.e.d.', 'hora'],
  ['500160', 'Fertirriego h.e.d.', 'hora'],
  ['500320', 'Fertitrincheo', 'hora'],
  ['823', 'Festivo promediado adm', 'hora'],
  ['1035', 'Festivo promediado adm El Refugio', 'dia'],
  ['783', 'Festivo promediado adm La Alegria', 'dia'],
  ['834', 'Festivo promediado adm Maria Laura', 'dia'],
  ['1023', 'Festivo promediado adm Maria Laura', 'dia'],
  ['908', 'Festivo promediado aprendiz finca', 'hora'],
  ['765', 'Festivo promediado transporte', 'hora'],
  ['970', 'Fumigacion al dia El Habra', 'hora'],
  ['15', 'Fumigacion carola', 'hora'],
  ['500248', 'Fumigacion de herbicida', 'hora'],
  ['500221', 'Fumigacion Elizabeth', 'hectarea'],
  ['500239', 'Fumigacion en plantilla', 'hora'],
  ['500244', 'Fumigacion nutrifoliar y dithane', 'hora'],
  ['368', 'Ganaderia', 'hora'],
  ['500412', 'Gastos de representacion', 'dia'],
  ['472', 'Gerente de calidad', 'hora'],
  ['421', 'Gerente de produccion', 'hora'],
  ['500477', 'Gerente de proyectos', 'dia'],
  ['10', 'Gerente general', 'hora'],
  ['1095', 'Gestion de calidad', 'hora'],
  ['1116', 'Gestion de calidad festivo', 'hora'],
  ['990', 'Gondulero', 'hora'],
  ['992', 'Gondulero h.e.d.', 'hora'],
  ['883', 'Guategrado', 'hora'],
  ['169', 'Hacer cajas', 'caja'],
  ['500246', 'Hechura de alberca', 'hora'],
  ['14', 'Hechura de cerca Elizabeth', 'hora'],
  ['500345', 'Hechura de cuneta', 'hora'],
  ['132', 'Hechura de cuneta Elizabeth', 'hora'],
  ['135', 'Hechura de cunetas El Refugio', 'hora'],
  ['500231', 'Hechura de desagüe', 'hora'],
  ['213', 'Hechura de estaca', 'hora'],
  ['952', 'Hechura de hueco para siembra', 'unidad'],
  ['274', 'Hechura de hueco para siembra al dia', 'hora'],
  ['500338', 'Hechura de pase cola', 'hora'],
  ['738', 'Hechura de portones', 'hora'],
  ['212', 'Hechura de sangria', 'hora'],
  ['500206', 'Hechura de trinchera', 'hora'],
  ['525', 'Hechura de trinchera h.e.d.', 'hora'],
  ['1087', 'Hechura de tulas de yumbolon', 'hora'],
  ['42', 'Hechura de zanja al dia', 'hora'],
  ['505', 'Hechura de zanja h.e.d.', 'hora'],
  ['733', 'Hechura y tapada de zanja', 'metro'],
  ['500307', 'Honorarios aux contable', 'dia'],
  ['500114', 'Horas diurnas', 'hora'],
  ['50093', 'Horas extras', 'hora'],
  ['500117', 'Horas extras nocturnas', 'hora'],
  ['500115', 'Horas nocturnas y recargos', 'hora'],
  ['500255', 'Horas. pend. herb. dominical', 'hora'],
  ['450', 'Horometro bulldozer', 'hora'],
  ['779', 'Incapacidad general adm', 'dia'],
  ['1131', 'Incapacidad por accidente adm', 'jornal'],
  ['152', 'Incapacidad por calamidad domestica', 'dia'],
  ['563', 'Incapacidad por valoracion medica', 'hora'],
  ['500473', 'Ingeniero agricola', 'dia'],
  ['994', 'Ingeniero agronomo', 'dia'],
  ['500266', 'Inspector de corte festivo', 'unidad'],
  ['1154', 'Inspector de fruta al dia', 'hora'],
  ['660', 'Instalacion de cable via', 'hora'],
  ['261', 'Instalacion de carpas moko', 'hora'],
  ['309', 'Instalacion de manguera', 'hora'],
  ['302', 'Instalacion de riego dominical', 'hora'],
  ['93', 'Instalacion de riego h.e.d.', 'hora'],
  ['349', 'Instalacion de riego proyecto', 'hora'],
  ['287', 'Instalacion de trampas', 'tonelada'],
  ['999', 'Integracion empresa adm', 'hora'],
  ['210', 'Interes de cesantias', 'prestacion'],
  ['500208', 'Inventario de carton', 'hora'],
  ['7', 'Inventario de fruta', 'racimo'],
  ['500308', 'Inyeccion de matas', 'hora'],
  ['50061', 'Jornales dia festivo', 'hora'],
  ['50060', 'Jornales ordinarios', 'hora'],
  ['482', 'Labores maiz', 'hora'],
  ['615', 'Labores maiz festivo', 'hora'],
  ['1118', 'Lavada de bolsas Don Gaspar dominical', 'hora'],
  ['500420', 'Lavada de costales', 'hora'],
  ['50072', 'Lavada de daipas', 'hora'],
  ['830', 'Lavada de envases', 'hora'],
  ['619', 'Lavada de estibas', 'hora'],
  ['690', 'Lavada de tuberias', 'hora'],
  ['392', 'Lavada de yumbolon', 'hora'],
  ['553', 'Lavada retroexcavadora', 'hora'],
  ['50047', 'Lavado de baberos', 'hora'],
  ['909', 'Levantamiento de troncones', 'hora'],
  ['555', 'Levante de manguera dominical', 'hora'],
  ['394', 'Levante de manguera festivo', 'hora'],
  ['558', 'Levante de manguera festivo h.e.d.', 'hora'],
  ['550', 'Levante de manguera h.e.d.', 'hora'],
  ['344', 'Levante de manguera plantilla', 'hora'],
  ['395', 'Levante de manguera plantilla festivo', 'hora'],
  ['381', 'Levante de manguera proyecto', 'hora'],
  ['396', 'Levante de manguera proyecto festivo', 'hora'],
  ['778', 'Lic maternidad aprendiz sena adm', 'dia'],
  ['120', 'Licencia', 'hora'],
  ['211', 'Licencia de maternidad', 'hora'],
  ['562', 'Licencia de maternidad adm', 'hora'],
  ['471', 'Licencia de paternidad', 'hora'],
  ['515', 'Licencia por luto adm', 'dia'],
  ['50058', 'Limpia a machete casa quinta', 'hora'],
  ['500165', 'Limpia a machete Elizabeth', 'hora'],
  ['378', 'Limpia a machete empacadora', 'hora'],
  ['176', 'Limpia a machete festivo', 'hora'],
  ['347', 'Limpia a machete plantilla', 'hora'],
  ['350', 'Limpia a machete proyecto', 'hora'],
  ['500366', 'Limpia canal con guadaña', 'metro'],
  ['500306', 'Limpia canal madrevieja', 'metro'],
  ['61', 'Limpia con guadaña al dia dominical', 'hora'],
  ['63', 'Limpia con guadaña al dia festivo', 'hora'],
  ['899', 'Limpia con guadaña El Habra al dia', 'hora'],
  ['911', 'Limpia con guadaña El Habra al dia festivo', 'hora'],
  ['993', 'Limpia con guadaña El Habra al dia h.e.d.', 'hora'],
  ['146', 'Limpia con guadaña El Refugio', 'hectarea'],
  ['127', 'Limpia con guadaña El Refugio por hora', 'hora'],
  ['500140', 'Limpia con guadaña Elizabeth', 'hectarea'],
  ['376', 'Limpia con guadaña festivo', 'hectarea'],
  ['117', 'Limpia con guadaña mla por hora', 'hora'],
  ['500132', 'Limpia con guadaña plantilla', 'hectarea'],
  ['500175', 'Limpia con guadaña plantilla al dia', 'hora'],
  ['377', 'Limpia con guadaña plantilla festivo al dia', 'hora'],
  ['367', 'Limpia con guadaña proyecto', 'hectarea'],
  ['384', 'Limpia con guadaña proyecto al dia', 'hora'],
  ['388', 'Limpia con guadaña proyecto al dia festivo', 'hora'],
  ['575', 'Limpia de camino', 'hora'],
  ['1060', 'Limpia de canal El Habra', 'hora'],
  ['1064', 'Limpia de canal palma al dia', 'hora'],
  ['255', 'Limpia de canal terciario', 'mts'],
  ['40', 'Limpia de cerca', 'hora'],
  ['13', 'Limpia de cerca Elizabeth', 'mts'],
  ['583', 'Limpia de cerca palma', 'hora'],
  ['50092', 'Limpia de cerca y linderos', 'hora'],
  ['142', 'Limpia de cheque', 'hora'],
  ['500219', 'Limpia de linderos', 'metro'],
  ['1126', 'Limpia de linderos El Habra', 'hora'],
  ['500133', 'Limpia de linderos proyecto', 'mts'],
  ['1113', 'Limpia de localidades', 'hora'],
  ['191', 'Limpia de malla', 'hora'],
  ['497', 'Limpia de manguera', 'hora'],
  ['143', 'Limpia de orilla de canal', 'hora'],
  ['500220', 'Limpia de piscina de riego', 'hora'],
  ['50091', 'Limpia de plantilla', 'hora'],
  ['1094', 'Limpia de ronda El Habra', 'hora'],
  ['159', 'Limpia de sequia', 'mts'],
  ['500476', 'Limpia de sequia al dia', 'hora'],
  ['500201', 'Limpia de vivero', 'hora'],
  ['50055', 'Limpia escobilla', 'mts'],
  ['603', 'Limpia frente finca', 'hora'],
  ['500100', 'Limpia terreno para trinche', 'hora'],
  ['500204', 'Limpia y pasada de tubo canal chirina', 'hora'],
  ['87', 'Llenada de bolsas vivero por hora', 'hora'],
  ['831', 'Llenada de rechazo dominical', 'hora'],
  ['577', 'Llenada de rechazo h.e.d.', 'hora'],
  ['426', 'Llenada de saco de materia organica', 'hora'],
  ['50057', 'Llenada de sacos de arena', 'hora'],
  ['500469', 'Mant cable turbina dominical', 'hora'],
  ['500332', 'Mant. canal de riego', 'hora'],
  ['500252', 'Mant. de retroexcabadora', 'hora'],
  ['500353', 'Mant. electrico', 'hora'],
  ['500322', 'Manten. matas lentas', 'hora'],
  ['500325', 'Mantenimiento bomba', 'hora'],
  ['500329', 'Mantenimiento buldozer', 'hora'],
  ['203', 'Mantenimiento canal de riego', 'hora'],
  ['265', 'Mantenimiento carpa moko', 'hora'],
  ['2415', 'Mantenimiento caseta motor', 'hora'],
  ['1114', 'Mantenimiento chapaleta', 'hora'],
  ['50045', 'Mantenimiento de aspersores', 'hora'],
  ['495', 'Mantenimiento de bodega', 'hora'],
  ['496', 'Mantenimiento de bodega h.e.d.', 'hora'],
  ['456', 'Mantenimiento de cable via h.e.d.', 'hora'],
  ['500363', 'Mantenimiento de canales', 'hora'],
  ['920', 'Mantenimiento de casa quinta', 'hora'],
  ['1142', 'Mantenimiento de cerca El Habra', 'hora'],
  ['855', 'Mantenimiento de cerca festivo', 'hora'],
  ['585', 'Mantenimiento de cerca maiz', 'hora'],
  ['584', 'Mantenimiento de cerca palma', 'hora'],
  ['818', 'Mantenimiento de cerca palma festivo', 'hora'],
  ['500145', 'Mantenimiento de drenajes', 'hora'],
  ['269', 'Mantenimiento de empacadora', 'hora'],
  ['1107', 'Mantenimiento de gondula', 'hora'],
  ['861', 'Mantenimiento de gondula dominical', 'hora'],
  ['641', 'Mantenimiento de manguera dominical', 'hora'],
  ['640', 'Mantenimiento de manguera dominical h.e.d.', 'hora'],
  ['637', 'Mantenimiento de manguera festivo', 'hora'],
  ['1033', 'Mantenimiento de parcela', 'hora'],
  ['50064', 'Mantenimiento de plantilla', 'hora'],
  ['325', 'Mantenimiento de plantilla festivo', 'hora'],
  ['1030', 'Mantenimiento de remolque', 'hora'],
  ['141', 'Mantenimiento de reservorio', 'hora'],
  ['891', 'Mantenimiento de riego adm Don Gaspar', 'hora'],
  ['892', 'Mantenimiento de riego adm La Alegria', 'hora'],
  ['500199', 'Mantenimiento de riego dominical', 'hora'],
  ['500095', 'Mantenimiento de riego Elizabeth', 'hora'],
  ['500170', 'Mantenimiento de riego festivo', 'hora'],
  ['249', 'Mantenimiento de riego proyecto', 'hora'],
  ['365', 'Mantenimiento de riego proyecto', 'hora'],
  ['2413', 'Mantenimiento de siembra', 'hora'],
  ['50082', 'Mantenimiento de tractor', 'hora'],
  ['500432', 'Mantenimiento electrico', 'hora'],
  ['280', 'Mantenimiento linderos', 'hora'],
  ['454', 'Mantenimiento maiz', 'hora'],
  ['500271', 'Marcacion canales', 'hora'],
  ['306', 'Marcacion de fruta barrida', 'hora'],
  ['391', 'Marcacion torres campo', 'hora'],
  ['500337', 'Matas saludables', 'hora'],
  ['283', 'Mecanico Palmawa', 'hora'],
  ['500274', 'Menor valor pagado dominical', 'hora'],
  ['521', 'Mezcla de fertilizante h.e.d.', 'hora'],
  ['500357', 'Mezcla para vivero', 'hora'],
  ['289', 'Mezcla para vivero festivo', 'hora'],
  ['500314', 'Moko', 'hora'],
  ['973', 'Montada de carton', 'hora'],
  ['972', 'Montada de carton h.e.d.', 'hora'],
  ['168', 'Montar y bajar tarimas', 'hora'],
  ['1134', 'Motorista El Habra', 'hora'],
  ['799', 'Motorista nocturno', 'hora'],
  ['825', 'Motorista nocturno h.e.n', 'hora'],
  ['795', 'Oficios varios abra dominical', 'hora'],
  ['816', 'Oficios varios abra festivo', 'hora'],
  ['500472', 'Oficios varios dominical', 'hora'],
  ['969', 'Oficios varios dominical h.e.d.', 'hora'],
  ['794', 'Oficios varios El Habra', 'hora'],
  ['913', 'Oficios varios festivo', 'dia'],
  ['500264', 'Oficios varios festivo', 'hora'],
  ['199', 'Oficios varios h.e.d.', 'hora'],
  ['264', 'Oficios varios nocturno', 'hora'],
  ['796', 'Oficios varios riviera', 'hora'],
  ['797', 'Oficios varios riviera dominical', 'hora'],
  ['824', 'Oficios varios riviera festivo', 'hora'],
  ['500285', 'Oper. retro dominical', 'hora'],
  ['500276', 'Oper. retroescav. sena', 'unidad'],
  ['500334', 'Operador de bulldozer', 'hora'],
  ['552', 'Operador de bulldozer dominical', 'hora'],
  ['613', 'Operador de bulldozer festivo', 'hora'],
  ['988', 'Operador de dron', 'jornal'],
  ['452', 'Operador de maquinaria', 'hora'],
  ['490', 'Operador de maquinaria dominical', 'hora'],
  ['594', 'Operador de maquinaria festivo', 'hora'],
  ['688', 'Operador de motosierra', 'hora'],
  ['801', 'Operador de motosierra dominical', 'hora'],
  ['879', 'Operador de motosierra festivo', 'hora'],
  ['881', 'Operador de motosierra h.e.d.', 'hora'],
  ['500286', 'Operador retro dominical', 'hora'],
  ['500457', 'Operador retro festivo', 'hora'],
  ['500335', 'Operador tractor', 'hora'],
  ['912', 'Organizacion de antenas', 'hora'],
  ['502', 'Organizacion de bodega', 'hora'],
  ['1085', 'Organizacion de fertilizantes', 'hora'],
  ['513', 'Organizacion de manguera', 'hora'],
  ['50080', 'Organizacion de tuberia', 'hora'],
  ['500111', 'Organizacion de vivero', 'hora'],
  ['322', 'Organizacion de yumbolon', 'hora'],
  ['500431', 'Organizacion papeleria', 'hora'],
  ['24123', 'Palero', 'hora'],
  ['589', 'Paletizacion de cajas', 'unidad'],
  ['500254', 'Parcela administrativa', 'hora'],
  ['50208', 'Parcela admistrativa la carola', 'hora'],
  ['500458', 'Parcela al dia', 'hora'],
  ['197', 'Parcela al dia El Refugio', 'hora'],
  ['35', 'Parcela al dia Elizabeth', 'hora'],
  ['500459', 'Parcela al dia festivo', 'hora'],
  ['65', 'Parcela al dia h.e.d.', 'hora'],
  ['864', 'Parcela al dia Maria Laura', 'hora'],
  ['617', 'Parcela al dia Maroma', 'hora'],
  ['618', 'Parcela al dia Maroma festivo', 'hora'],
  ['500147', 'Parcela al dia plantilla', 'hora'],
  ['500367', 'Parcela combinada', 'hectarea'],
  ['116', 'Parcela combinada dominical', 'hectarea'],
  ['663', 'Parcela combinada El Refugio', 'hectarea'],
  ['500190', 'Parcela combinada festivo', 'hectarea'],
  ['500411', 'Parcela Don Gaspar', 'hectarea'],
  ['500426', 'Parcela simultanea', 'hectarea'],
  ['556', 'Parcela simultanea dominical', 'hectarea'],
  ['500434', 'Parcela simultanea Elizabeth', 'hectarea'],
  ['500185', 'Parcela simultanea festivo', 'hectarea'],
  ['595', 'Parcela simultanea Maroma', 'hectarea'],
  ['500321', 'Pegada de carton', 'hora'],
  ['914', 'Pegada de carton empacadora movil', 'hora'],
  ['268', 'Pelota despeche', 'hora'],
  ['422', 'Pendiente pago incapacidad', 'hora'],
  ['285', 'Pepeo', 'bulto'],
  ['277', 'Pepeo al dia', 'hora'],
  ['648', 'Permiso adm', 'dia'],
  ['145', 'Permiso por examenes de ingreso', 'hora'],
  ['184', 'Permiso por terapias', 'hora'],
  ['1081', 'Peso de fruta palma', 'hora'],
  ['1458', 'Pintada areas y localidades', 'hora'],
  ['1024', 'Pintada de garruchas', 'hora'],
  ['500216', 'Pintura de tuberia y aseo bodega', 'hora'],
  ['500126', 'Pintura de tuberia.', 'hora'],
  ['518', 'Pintura dominical', 'hora'],
  ['839', 'Pintura Don Gaspar', 'hora'],
  ['1089', 'Pintura El Refugio', 'hora'],
  ['858', 'Pintura festivo', 'hora'],
  ['500', 'Pintura h.e.d.', 'hora'],
  ['840', 'Pintura h.e.d. Don Gaspar', 'hora'],
  ['1101', 'Pintura Maria Laura', 'hora'],
  ['379', 'Plateo con guadaña al dia', 'hora'],
  ['1104', 'Plateo con guadaña El Habra al dia', 'hora'],
  ['500364', 'Plateo con machete al dia', 'hora'],
  ['1103', 'Plateo con machete El Habra al dia', 'hora'],
  ['380', 'Plateo quimico', 'hora'],
  ['1106', 'Plateo quimico El Habra al dia', 'hora'],
  ['263', 'Poda', 'hora'],
  ['290', 'Poda de matas', 'hora'],
  ['375', 'Poda de palma', 'palma'],
  ['467', 'Poda de palma al dia', 'hora'],
  ['500328', 'Podada de single', 'hora'],
  ['1147', 'Polinizacion El Habra', 'hora'],
  ['164', 'Postura de periodico', 'hora'],
  ['157', 'Postura de puente', 'hora'],
  ['144', 'Precalibracion dominical', 'hora'],
  ['500466', 'Precalibracion El Refugio', 'hora'],
  ['500171', 'Precalibracion Elizabeth', 'hora'],
  ['67', 'Precalibracion festivo', 'hora'],
  ['607', 'Precalibracion Maroma', 'hora'],
  ['500294', 'Precorte', 'hora'],
  ['16', 'Precorte pendiente', 'mts'],
  ['500251', 'Predesmache', 'hora'],
  ['2898', 'Prensada de bolsas', 'hora'],
  ['50074', 'Preparacion bolsa de campo', 'hora'],
  ['500097', 'Preparacion de cintas', 'hora'],
  ['1047', 'Preparacion de material vivero', 'hora'],
  ['500099', 'Preparacion de nylon', 'hora'],
  ['500225', 'Preparacion de suelos', 'hora'],
  ['500130', 'Preparacion de yumbolon', 'hora'],
  ['204', 'Prima de servicios', 'prestacion'],
  ['59', 'Programa de recuperacion', 'hora'],
  ['500189', 'Promedio bolsa y proteclon', 'caja'],
  ['500188', 'Promedio llenada de canastilla', 'caja'],
  ['500356', 'Proteccion bolsa', 'hora'],
  ['500416', 'Proteccion de fruta', 'hora'],
  ['677', 'Proteccion de fruta El Refugio', 'hectarea'],
  ['500323', 'Proteccion quema de sol', 'unidad'],
  ['545', 'Quema de madera', 'hora'],
  ['266', 'Quema de mapaitero', 'hora'],
  ['43', 'Quemada de plastico', 'mts'],
  ['190', 'Quitada de cerca', 'hora'],
  ['500250', 'Quitada de techo', 'hora'],
  ['500268', 'Rastrillado de canales', 'unidad'],
  ['50070', 'Rastrillo', 'hora'],
  ['488', 'Realce', 'hectarea'],
  ['500288', 'Realce al dia', 'hora'],
  ['500158', 'Realce de plantilla al dia', 'hora'],
  ['128', 'Realce El Refugio', 'hora'],
  ['122', 'Realce Elizabeth', 'hora'],
  ['500451', 'Realce festivo', 'hora'],
  ['383', 'Realce plantilla proyecto', 'hora'],
  ['676', 'Reamarre al dia El Refugio', 'hora'],
  ['54', 'Recargo nocturno regadores', 'hora'],
  ['47', 'Recava canal secundario', 'mts'],
  ['81', 'Recava de canal al dia', 'hora'],
  ['500113', 'Recava del canal de riego', 'hora'],
  ['915', 'Recibo y reubicacion tanques e.m. dominical', 'hora'],
  ['442', 'Reciclaje de bolsas', 'unidad'],
  ['167', 'Reciclaje de cintas', 'hora'],
  ['50089', 'Reciclaje de soga de campo', 'hora'],
  ['798', 'Reciclaje de yumbolon', 'hora'],
  ['500157', 'Reciclaje plasticos de campo', 'hora'],
  ['967', 'Recogida alambre de cerca', 'hora'],
  ['732', 'Recogida de aspersores', 'hora'],
  ['579', 'Recogida de caracol', 'hora'],
  ['431', 'Recogida de gravilla', 'hora'],
  ['500333', 'Recogida de madera', 'hora'],
  ['315', 'Recogida de manguera', 'hora'],
  ['390', 'Recogida de manguera proyecto', 'hora'],
  ['443', 'Recogida de tuberias', 'hora'],
  ['369', 'Recogida en acopio', 'tonelada'],
  ['1129', 'Recogida en acopio al dia', 'hora'],
  ['544', 'Recogida en acopio dominical', 'tonelada'],
  ['863', 'Recogida en acopio festivo', 'tonelada'],
  ['500365', 'Recogida soga de campo', 'hora'],
  ['438', 'Recoleccion de antenas', 'hora'],
  ['449', 'Recoleccion de basura', 'hora'],
  ['652', 'Recoleccion de bolsa y yumbolon', 'hora'],
  ['1112', 'Recoleccion de cables', 'hora'],
  ['296', 'Recoleccion de insumos parcela', 'hora'],
  ['500354', 'Recoleccion de madera', 'hora'],
  ['50054', 'Recoleccion de materiales de riego', 'hora'],
  ['591', 'Recoleccion de rechazo', 'hora'],
  ['600', 'Recoleccion de residuos solidos', 'hora'],
  ['50088', 'Recoleccion de semillas', 'hora'],
  ['1052', 'Recoleccion de semillas vivero', 'hora'],
  ['500391', 'Recoleccion de soga', 'hora'],
  ['174', 'Recoleccion de yumbolon', 'hora'],
  ['1078', 'Reconstruccion de canal El Habra al dia', 'hora'],
  ['500205', 'Reconstruccion de puente', 'hora'],
  ['500243', 'Reconstruccion de tuberia', 'hora'],
  ['1003', 'Recuperacion de area con vastagos', 'hora'],
  ['500384', 'Recuperacion de bolsas por hora', 'hora'],
  ['1067', 'Recuperacion de carton', 'hora'],
  ['885', 'Recuperacion de troncon', 'hora'],
  ['884', 'Reenvase de acidos', 'hora'],
  ['500373', 'Regada de fibra', 'hora'],
  ['406', 'Regada de gravilla', 'hora'],
  ['835', 'Regada de relleno', 'hora'],
  ['500421', 'Regada de tierra', 'hora'],
  ['859', 'Regada de tierra festivo', 'hora'],
  ['980', 'Relleno de tierra', 'hora'],
  ['538', 'Relleno de tierra empacadora', 'hora'],
  ['747', 'Reparacion de tuberia', 'hora'],
  ['206', 'Reparcheo herbicida', 'hora'],
  ['780', 'Repase labor mala calidad deshoje', 'hora'],
  ['665', 'Repase labor mala calidad maleza', 'hectarea'],
  ['793', 'Repase labor mala calidad parcela', 'hora'],
  ['517', 'Repeso de rechazo', 'hora'],
  ['62', 'Repique cepa corte o viento', 'hora'],
  ['649', 'Repique de arbol caido festivo', 'hora'],
  ['198', 'Repique de hojas', 'hora'],
  ['929', 'Repique de hojas festivo', 'hora'],
  ['991', 'Repique de hojas h.e.d.', 'hora'],
  ['651', 'Repique de matas Maroma', 'hora'],
  ['721', 'Repique de plastico', 'hora'],
  ['979', 'Repique de pulpa crema', 'hora'],
  ['338', 'Repique de racimos', 'hora'],
  ['500137', 'Repique de rebrote', 'hora'],
  ['348', 'Repique de rebrote plantilla', 'hora'],
  ['500129', 'Resiembra de cabezas', 'unidad'],
  ['355', 'Resiembra de cabezas plantilla', 'unidad'],
  ['1017', 'Resiembra de palma', 'hora'],
  ['50087', 'Resiembra de plantilla', 'hora'],
  ['50046', 'Resiembra de puyon', 'unidad'],
  ['429', 'Resiembra de semillas', 'unidad'],
  ['500156', 'Resiembra de troncon Elizabeth', 'unidad'],
  ['1120', 'Retiro de madera', 'hora'],
  ['1125', 'Retiro de madera Don Gaspar', 'hora'],
  ['1127', 'Retiro de madera Don Gaspar festivo', 'hora'],
  ['1121', 'Retiro de madera festivo', 'hora'],
  ['997', 'Retroactivo incremento salarial adm', 'dia'],
  ['790', 'Reubicacion de manguera', 'hora'],
  ['430', 'Reunion administrativa', 'hora'],
  ['500166', 'Riego dominical Elizabeth', 'hora'],
  ['971', 'Riego El Habra', 'hora'],
  ['974', 'Riego El Habra dominical', 'hora'],
  ['989', 'Riego El Habra festivo', 'hora'],
  ['500435', 'Riego Elizabeth', 'hora'],
  ['73', 'Riego Elizabeth cristina', 'hora'],
  ['500163', 'Riego festivo Elizabeth', 'hora'],
  ['500162', 'Riego festivo nocturno', 'hora'],
  ['89', 'Riego h.e.n.', 'hora'],
  ['68', 'Riego h.e.n. festivo', 'hora'],
  ['354', 'Riego la carola', 'hora'],
  ['475', 'Riego maiz', 'hora'],
  ['634', 'Riego maiz dominical', 'hora'],
  ['635', 'Riego maiz festivo', 'hora'],
  ['74', 'Riego nocturno', 'hora'],
  ['826', 'Riego nocturno h.e.n.', 'hora'],
  ['50036', 'Riego por desnivel', 'hora'],
  ['886', 'Sacada de alterones', 'hora'],
  ['500296', 'Sacada de fruta', 'hora'],
  ['1056', 'Sacada de fruta pulpa crema', 'hora'],
  ['1128', 'Sacada de fruta suelta', 'hora'],
  ['588', 'Sacada de limo', 'hora'],
  ['134', 'Sacada de malla', 'hora'],
  ['509', 'Sacada de manguera', 'hora'],
  ['646', 'Sacada de material chatarra', 'hora'],
  ['50095', 'Sacada de postes de cable aereo', 'dia'],
  ['500281', 'Sacada de relleno', 'hora'],
  ['500238', 'Sacada de semillas', 'hora'],
  ['654', 'Sacada de troncones', 'unidad'],
  ['559', 'Sacada de tuberia', 'metro'],
  ['500256', 'Sacada de tuberia al dia', 'hora'],
  ['500414', 'Salario administracion', 'dia'],
  ['934', 'Saldo pendiente aprendiz sena festivo', 'hora'],
  ['500327', 'Saldo pendiente aseo empacadora', 'hora'],
  ['871', 'Saldo pendiente auxiliar de empacadora', 'hora'],
  ['500375', 'Saldo pendiente ayudante de albañil', 'hora'],
  ['1012', 'Saldo pendiente ayudante de fumigacion aerea', 'hora'],
  ['77', 'Saldo pendiente botada de vastago', 'unidad'],
  ['500377', 'Saldo pendiente cargue de cajas', 'hora'],
  ['254', 'Saldo pendiente celaduria', 'hora'],
  ['500326', 'Saldo pendiente control de maleza', 'unidad'],
  ['784', 'Saldo pendiente corte promedio', 'unidad'],
  ['932', 'Saldo pendiente cosecha', 'tonelada'],
  ['965', 'Saldo pendiente descargue de carton', 'hora'],
  ['500348', 'Saldo pendiente deshoje', 'unidad'],
  ['776', 'Saldo pendiente desmache', 'unidad'],
  ['500273', 'Saldo pendiente desmache', 'hectarea'],
  ['1054', 'Saldo pendiente drenajes', 'hora'],
  ['873', 'Saldo pendiente embolse y amarre cinta morada', 'unidad'],
  ['10002', 'Saldo pendiente festivo promediado', 'hora'],
  ['12', 'Saldo pendiente fumigacion', 'hora'],
  ['961', 'Saldo pendiente horometro maquinaria', 'hora'],
  ['1074', 'Saldo pendiente licencia por luto', 'hora'],
  ['960', 'Saldo pendiente maquinaria', 'hora'],
  ['500347', 'Saldo pendiente parcela', 'unidad'],
  ['21', 'Saldo pendiente parcela administrativa', 'hora'],
  ['956', 'Saldo pendiente proteccion de fruta', 'hora'],
  ['876', 'Saldo pendiente resiembras', 'hora'],
  ['762', 'Saldo pendiente riego', 'hora'],
  ['1124', 'Saldo pendiente viaje tractomula', 'dia'],
  ['764', 'Saldo pendiente yumbolon', 'racimo'],
  ['500376', 'Saldo regada de fibra', 'hora'],
  ['1057', 'Sanidad El Habra', 'hora'],
  ['1097', 'Sanidad vegetal', 'hora'],
  ['1105', 'Seleccion de madera', 'hora'],
  ['661', 'Seleccion de matas', 'hora'],
  ['685', 'Seleccion de matas El Refugio', 'hora'],
  ['500237', 'Seleccion fertiliza spalderos', 'hora'],
  ['457', 'Siembra de maiz', 'hora'],
  ['364', 'Siembra de meristemos', 'hora'],
  ['820', 'Siembra de palma', 'hora'],
  ['822', 'Siembra de palma dominical', 'hora'],
  ['878', 'Siembra de palma festivo', 'hora'],
  ['821', 'Siembra de palma h.e.d.', 'hora'],
  ['55', 'Siembra de plantas vivero', 'hora'],
  ['44', 'Siembra de semillas', 'semilla'],
  ['41', 'Siembra de troncones', 'unidad'],
  ['1053', 'Siembra de vivero', 'unidad'],
  ['124', 'Siembra y llenada de bolsas vivero', 'hora'],
  ['500440', 'Soldador', 'dia'],
  ['420', 'Soldadura', 'hora'],
  ['926', 'Soltura de cable via', 'hora'],
  ['22222', 'Supervisor de calidad', 'hora'],
  ['50097', 'Supervisor de campo', 'hora'],
  ['500265', 'Supervisor de corte festivo', 'hora'],
  ['485', 'Supervisor de empacadora', 'hora'],
  ['653', 'Supervisor de riego', 'hora'],
  ['500207', 'Supervisor finca La Alegria', ''],
  ['514', 'Supervisor zona sur', 'hora'],
  ['896', 'Surtir vivero', 'hora'],
  ['94', 'Suspencion de contrato', 'hora'],
  ['500233', 'Tapada de canal', 'hora'],
  ['500278', 'Tapada de sanja', 'metro'],
  ['500290', 'Tapada de tuberia', 'hora'],
  ['366', 'Tapada de tuberia proyecto', 'hora'],
  ['500292', 'Tapada de zanja', 'hora'],
  ['500235', 'Terminacion de contrato', 'hora'],
  ['387', 'Tiempo de espera fumigacion', 'hora'],
  ['548', 'Toma de muestras', 'hora'],
  ['686', 'Topyban al dia', 'hora'],
  ['500304', 'Tractorista', 'hora'],
  ['500437', 'Tractorista dominical', 'hora'],
  ['968', 'Tractorista dominical h.e.d.', 'hora'],
  ['817', 'Tractorista festivo', 'hora'],
  ['789', 'Tractorista h.e.d.', 'hora'],
  ['500214', 'Tranporte a las flores carton', 'unidad'],
  ['500305', 'Transbordo de cajas', 'hora'],
  ['1042', 'Transbordo de cajas h.e.d.', 'hora'],
  ['500213', 'Transp materiales empacadora', 'hora'],
  ['500212', 'Transporte a las flores (tanques)', 'unidad'],
  ['500211', 'Transporte de frutas', 'unidad'],
  ['500269', 'Transporte de insumos y carton', 'hora'],
  ['1092', 'Transporte de plantas', 'hora'],
  ['500301', 'Transporte de semillas', 'hora'],
  ['1048', 'Transporte de semillas vivero', 'hora'],
  ['1140', 'Transporte de tanques de fumigacion', 'hora'],
  ['50090', 'Transporte de tubos', 'unidad'],
  ['917', 'Transporte de turbina', 'hora'],
  ['500317', 'Trapero quimico', 'hora'],
  ['500177', 'Traslado de cisco vivero', 'hora'],
  ['501', 'Traslado de insumos', 'hora'],
  ['930', 'Traslado de madera dominical', 'hora'],
  ['1038', 'Traslado de material moko', 'hora'],
  ['1039', 'Traslado de material para vivero', 'hora'],
  ['1152', 'Traslado de porton', 'hora'],
  ['1008', 'Traslado de rechazo', 'hora'],
  ['953', 'Traslado de tablas', 'hora'],
  ['906', 'Traslado empacadora movil', 'hora'],
  ['464', 'Traslado fertilizante', 'tonelada'],
  ['500407', 'Trincheo', 'hectarea'],
  ['500313', 'Trincheo al dia', 'hora'],
  ['500196', 'Trincheo Elizabeth', 'hectarea'],
  ['500258', 'Tumba de area para siembra', 'hora'],
  ['500340', 'Tumbada de cerca', 'hora'],
  ['500155', 'Tutor parcela combinada', 'hora'],
  ['424', 'Viaje camion', 'dia'],
  ['50079', 'Viaje de boñiga', 'unidad'],
  ['425', 'Viaje tractomula', 'dia'],
  ['759', 'Viaje tractomula lechero', 'dia'],
  ['500470', 'Viajes', 'dia'],
  ['500471', 'Viaticos', 'dia'],
  ['516', 'Vigorizacion', 'hora'],
  ['1148', 'Vivero Don Gaspar', 'hora'],
  ['580', 'Vivero palma', 'hora'],
  ['616', 'Vivero palma dominical', 'hora'],
  ['601', 'Vivero palma festivo', 'hora'],
  ['851', 'Yumbolon cinta amarilla festivo', 'unidad'],
  ['847', 'Yumbolon cinta azul festivo', 'unidad'],
  ['743', 'Yumbolon cinta beige', 'unidad'],
  ['853', 'Yumbolon cinta beige festivo', 'unidad'],
  ['848', 'Yumbolon cinta blanca festivo', 'unidad'],
  ['846', 'Yumbolon cinta cafe festivo', 'unidad'],
  ['692', 'Yumbolon cinta gris', 'racimo'],
  ['844', 'Yumbolon cinta gris festivo', 'unidad'],
  ['744', 'Yumbolon cinta mecate', 'unidad'],
  ['854', 'Yumbolon cinta mecate festivo', 'unidad'],
  ['850', 'Yumbolon cinta morada festivo', 'unidad'],
  ['849', 'Yumbolon cinta negra festivo', 'unidad'],
  ['852', 'Yumbolon cinta roja festivo', 'unidad'],
  ['845', 'Yumbolon cinta verde festivo', 'unidad'],
  ['1266', 'Yumbolon por hectarea', 'hectarea'],
];

const repetidos = new Set();
{ const vistos = new Set(); for (const [, n] of FILAS) { const k = n.toLowerCase(); if (vistos.has(k)) repetidos.add(k); vistos.add(k); } }

export const LABORES_NOMINA = FILAS.map(([codigo, nombre, und]) => ({
  codigo, nombre, und,
  unidad: UNIDADES[und] || und || 'unidades',
  porLote: POR_LOTE.has(und),
  // Dos labores con el mismo nombre se distinguen por el código.
  etiqueta: repetidos.has(nombre.toLowerCase()) ? `${nombre} (${codigo})` : nombre,
}));
