// Labores de nómina para la jornada: [código, labor, unidad de pago]. Salen del registro de
// labores de Don Gaspar (dic-2025 a sep-2026), de la más a la menos usada, sin las variantes
// que define la fecha (festivo, dominical, H.e.d.) ni conceptos que no son labor (auxilios,
// incapacidades, saldos). La unidad es la que más se paga para ese código.

export const LABORES_NOMINA = [
  ['334', 'Corte caja integral', 'cajas'],
  ['23', 'Deshoje', 'ha'],
  ['336', 'Corte promedio', 'cajas'],
  ['50381', 'Desflore e identificación', 'ha'],
  ['58', 'Coordinador de campo', 'horas'],
  ['72', 'Riego', 'horas'],
  ['500277', 'Corte al día', 'horas'],
  ['162', 'Administrador finca', 'horas'],
  ['50096', 'Celaduría', 'horas'],
  ['500341', 'Coordinador de empacadora', 'horas'],
  ['445', 'Control de maleza al día', 'horas'],
  ['500425', 'Almacenista', 'horas'],
  ['258', 'Botada de vástago', 'unidades'],
  ['500349', 'Limpia con guadaña al día', 'horas'],
  ['3', 'Coordinador general', 'horas'],
  ['5', 'Desmache con palín', 'ha'],
  ['104', 'Chapia de canal', 'metros'],
  ['70', 'Motorista', 'horas'],
  ['754', 'Embolse y amarre cinta morada', 'racimos'],
  ['750', 'Embolse y amarre cinta café', 'racimos'],
  ['755', 'Embolse y amarre cinta amarilla', 'racimos'],
  ['756', 'Embolse y amarre cinta roja', 'racimos'],
  ['751', 'Embolse y amarre cinta azul', 'racimos'],
  ['752', 'Embolse y amarre cinta blanca', 'racimos'],
  ['656', 'Aplicación de fertilizante und', 'bultos'],
  ['96', 'Levante de manguera', 'horas'],
  ['893', 'Mantenimiento de riego adm. Maroma', 'horas'],
  ['620', 'Auxiliar de casino', 'horas'],
  ['749', 'Embolse y amarre cinta verde', 'racimos'],
  ['696', 'Yumbolón cinta blanca', 'racimos'],
  ['1028', 'Control de maleza Moko', 'horas'],
  ['753', 'Embolse y amarre cinta negra', 'racimos'],
  ['492', 'Corte promedio rechazo', 'cajas'],
  ['995', 'Ayudante de fumigación aérea', 'horas'],
  ['500302', 'Limpia con guadaña', 'ha'],
  ['699', 'Yumbolón cinta amarilla', 'racimos'],
  ['596', 'Mantenimiento de manguera', 'horas'],
  ['695', 'Yumbolón cinta azul', 'racimos'],
  ['561', 'Corte promedio cablero', 'cajas'],
  ['693', 'Yumbolón cinta verde', 'racimos'],
  ['698', 'Yumbolón cinta morada', 'racimos'],
  ['1182', 'Mantenimiento de pediluvio Moko', 'horas'],
  ['1029', 'Deshoje Moko al día', 'horas'],
  ['945', 'Corte promedio bioseguridad', 'cajas'],
  ['500203', 'Operador retroexcavadora', 'horas'],
  ['404', 'Bioseguridad', 'horas'],
  ['189', 'Cablero', 'horas'],
  ['256', 'Mantenimiento de riego', 'horas'],
  ['50050', 'Control de Moko', 'horas'],
  ['259', 'Aseo de empacadora', 'horas'],
  ['955', 'Protección de fruta al día', 'horas'],
  ['50035', 'Resiembra de troncón', 'unidades'],
  ['700', 'Yumbolón cinta roja', 'racimos'],
  ['694', 'Yumbolón cinta café', 'racimos'],
  ['697', 'Yumbolón cinta negra', 'racimos'],
  ['2412', 'Mantenimiento de resiembra', 'horas'],
  ['317', 'Mantenimiento de riego adm.', 'horas'],
  ['50041', 'Llenada de rechazo', 'horas'],
  ['500112', 'Limpia de jarillón', 'horas'],
  ['1119', 'Pegada de yumbolón', 'horas'],
  ['1117', 'Sanidad vegetal El Habra', 'horas'],
  ['500319', 'Desbejuque', 'ha'],
  ['9887', 'Repique de matas', 'horas'],
  ['500174', 'Mantenimiento de infraestructura', 'horas'],
  ['500210', 'Chapia de canal al día', 'horas'],
  ['158', 'Vivero', 'horas'],
  ['1229', 'Coordinador de bioseguridad', 'horas'],
  ['370', 'Protección quema de sol al día', 'horas'],
  ['50053', 'Aseo de bodega', 'horas'],
  ['50083', 'Aseo de plantación', 'horas'],
  ['500179', 'Corte promedio al día', 'horas'],
  ['494', 'Mantenimiento de retro', 'horas'],
  ['316', 'Siembra', 'unidades'],
  ['500462', 'Corte mercado nacional', 'horas'],
  ['1062', 'Control de insectos El Habra', 'horas'],
  ['500262', 'Desmache al día', 'horas'],
  ['130', 'Limpia de linderos al día', 'horas'],
  ['1026', 'Fertilización El Habra', 'horas'],
  ['1144', 'Aplicación foliar El Habra', 'horas'],
  ['48', 'Recava de canal', 'metros'],
  ['500393', 'Control de población', 'horas'],
  ['1075', 'Desbejuque Moko al día', 'horas'],
  ['1173', 'Chapia de canal Moko al día', 'horas'],
  ['50049', 'Limpia de canal de riego', 'horas'],
  ['1206', 'Siembra de vivero al día', 'horas'],
  ['1249', 'Previvero de palma', 'horas'],
  ['500352', 'Deshoje al día', 'horas'],
  ['444', 'Control de maleza', 'ha'],
  ['500300', 'Hechura de puente', 'horas'],
  ['160', 'Aseo general', 'horas'],
  ['180', 'Horómetro retroexcavadora', 'horas'],
  ['639', 'Aseo cable vía', 'horas'],
  ['50077', 'Conteo de cinta', 'horas'],
  ['957', 'Botada de vástago al día', 'horas'],
  ['500181', 'Desbejuque al día', 'horas'],
  ['401', 'Recuperación de yumbolón', 'horas'],
  ['500249', 'Mantenimiento de vivero', 'horas'],
  ['50078', 'Mantenimiento de garruchas', 'horas'],
  ['22', 'Reamarre al día', 'horas'],
  ['235', 'Descargue de cartón', 'horas'],
  ['500372', 'Acarreo de semillas', 'horas'],
  ['895', 'Mantenimiento de riego adm. El Refugio', 'horas'],
  ['386', 'Limpia de reservorio', 'horas'],
  ['500361', 'Mantenimiento de guadaña', 'horas'],
  ['83', 'Instalación de riego', 'horas'],
  ['205', 'Resiembras', 'horas'],
  ['1153', 'Marcación de espacios para siembra', 'horas'],
  ['962', 'Aseo de casa administrativa', 'horas'],
  ['785', 'Corte promedio rechazo al día', 'unidades'],
  ['1044', 'Mantenimiento de cerca Moko', 'horas'],
  ['310', 'Transporte de matas', 'horas'],
  ['500417', 'Recolección de plástico', 'horas'],
  ['500397', 'Desguasque', 'ha'],
  ['298', 'Clasificación de yumbolón', 'horas'],
  ['500180', 'Desguasque al día', 'horas'],
  ['123', 'Arranque de troncón', 'horas'],
  ['82', 'Mantenimiento de cable vía', 'horas'],
  ['500423', 'Acarreo de troncón', 'horas'],
  ['3335', 'Hechura de escalera', 'horas'],
  ['951', 'Botada de fruta pulpa crema', 'horas'],
  ['126', 'Pintura', 'horas'],
  ['69', 'Mantenimiento de motor', 'horas'],
  ['1166', 'Descargue de fertilizante al día', 'horas'],
  ['1100', 'Limpia de linderos Moko al día', 'horas'],
  ['621', 'Mantenimiento de pediluvio', 'horas'],
  ['1011', 'Reamarre y desvío', 'horas'],
  ['38', 'Aplicación de fertilizante al día', 'horas'],
  ['500362', 'Agricultura', 'horas'],
  ['1043', 'Colocación de pase cola', 'horas'],
  ['163', 'Mantenimiento de cerca', 'horas'],
  ['161', 'Engrase de cable vía', 'horas'],
  ['905', 'Aseo de empacadora móvil', 'horas'],
  ['118', 'Limpia guadaña empacadora', 'horas'],
  ['192', 'Elaboración de vivero', 'horas'],
  ['2424', 'Precalibración', 'horas'],
  ['1027', 'Colocación de carpa Moko', 'horas'],
  ['272', 'Acarreo de matas para siembra', 'horas'],
  ['1187', 'Ayudante de cosecha', 'horas'],
  ['500234', 'Desagüe de canal', 'horas'],
  ['1093', 'Desbejuque al día El Habra', 'horas'],
  ['292', 'Identificación de cintas', 'horas'],
  ['30', 'Colocación de yumbolón', 'unidades'],
  ['500279', 'Llenada de bolsas vivero', 'unidades'],
  ['1146', 'Organización de casino', 'horas'],
  ['687', 'Arreglo de patio racimo', 'horas'],
  ['981', 'Repique de árbol caído', 'horas'],
  ['26', 'Limpia a machete', 'horas'],
  ['534', 'Siembra al día', 'horas'],
  ['894', 'Mantenimiento de riego adm. María Laura', 'horas'],
  ['34', 'Hechura de antenas al día', 'horas'],
  ['1058', 'Mantenimiento de riego El Habra', 'horas'],
  ['1176', 'Mantenimiento de empacadora móvil', 'horas'],
  ['156', 'Aseo de patio', 'horas'],
  ['658', 'Preparación de vivero', 'horas'],
  ['745', 'Hechura de zanja', 'metros'],
  ['1197', 'Apoyo cosecha Moko', 'horas'],
  ['1231', 'Limpia de área de motor', 'horas'],
  ['50', 'Oficios varios', 'horas'],
  ['1014', 'Corte promedio Moko', 'cajas'],
  ['50076', 'Botada de basura', 'horas'],
  ['1262', 'Aseo de área de empacadora', 'horas'],
].map(([codigo, nombre, unidad]) => ({ codigo, nombre, unidad }));
